// AUTO-GENERATED by Scripts/generate.py — DO NOT EDIT.
// Re-run `Scripts/sync-symbols.sh && Scripts/generate.py` to regenerate.

import Foundation
import CornucopiaSymbolsCore

public enum Feather: String, CornucopiaSymbol, Sendable {

    public static let setName = "Feather"
    public static let bundle = resolveCornucopiaBundle(
        named: "CornucopiaSymbols_CornucopiaSymbolsFeather",
        fallback: .module
    )

    case activity
    case airplay
    case alertCircle = "alert-circle"
    case alertOctagon = "alert-octagon"
    case alertTriangle = "alert-triangle"
    case alignCenter = "align-center"
    case alignJustify = "align-justify"
    case alignLeft = "align-left"
    case alignRight = "align-right"
    case anchor
    case aperture
    case archive
    case arrowDownCircle = "arrow-down-circle"
    case arrowDownLeft = "arrow-down-left"
    case arrowDownRight = "arrow-down-right"
    case arrowDown = "arrow-down"
    case arrowLeftCircle = "arrow-left-circle"
    case arrowLeft = "arrow-left"
    case arrowRightCircle = "arrow-right-circle"
    case arrowRight = "arrow-right"
    case arrowUpCircle = "arrow-up-circle"
    case arrowUpLeft = "arrow-up-left"
    case arrowUpRight = "arrow-up-right"
    case arrowUp = "arrow-up"
    case atSign = "at-sign"
    case award
    case barChart2 = "bar-chart-2"
    case barChart = "bar-chart"
    case batteryCharging = "battery-charging"
    case battery
    case bellOff = "bell-off"
    case bell
    case bluetooth
    case bold
    case bookOpen = "book-open"
    case book
    case bookmark
    case box
    case briefcase
    case calendar
    case cameraOff = "camera-off"
    case camera
    case cast
    case checkCircle = "check-circle"
    case checkSquare = "check-square"
    case check
    case chevronDown = "chevron-down"
    case chevronLeft = "chevron-left"
    case chevronRight = "chevron-right"
    case chevronUp = "chevron-up"
    case chevronsDown = "chevrons-down"
    case chevronsLeft = "chevrons-left"
    case chevronsRight = "chevrons-right"
    case chevronsUp = "chevrons-up"
    case chrome
    case circle
    case clipboard
    case clock
    case cloudDrizzle = "cloud-drizzle"
    case cloudLightning = "cloud-lightning"
    case cloudOff = "cloud-off"
    case cloudRain = "cloud-rain"
    case cloudSnow = "cloud-snow"
    case cloud
    case code
    case codepen
    case codesandbox
    case coffee
    case columns
    case command
    case compass
    case copy
    case cornerDownLeft = "corner-down-left"
    case cornerDownRight = "corner-down-right"
    case cornerLeftDown = "corner-left-down"
    case cornerLeftUp = "corner-left-up"
    case cornerRightDown = "corner-right-down"
    case cornerRightUp = "corner-right-up"
    case cornerUpLeft = "corner-up-left"
    case cornerUpRight = "corner-up-right"
    case cpu
    case creditCard = "credit-card"
    case crop
    case crosshair
    case database
    case delete
    case disc
    case divideCircle = "divide-circle"
    case divideSquare = "divide-square"
    case divide
    case dollarSign = "dollar-sign"
    case downloadCloud = "download-cloud"
    case download
    case dribbble
    case droplet
    case edit2 = "edit-2"
    case edit3 = "edit-3"
    case edit
    case externalLink = "external-link"
    case eyeOff = "eye-off"
    case eye
    case facebook
    case fastForward = "fast-forward"
    case feather
    case figma
    case fileMinus = "file-minus"
    case filePlus = "file-plus"
    case fileText = "file-text"
    case file
    case film
    case filter
    case flag
    case folderMinus = "folder-minus"
    case folderPlus = "folder-plus"
    case folder
    case framer
    case frown
    case gift
    case gitBranch = "git-branch"
    case gitCommit = "git-commit"
    case gitMerge = "git-merge"
    case gitPullRequest = "git-pull-request"
    case github
    case gitlab
    case globe
    case grid
    case hardDrive = "hard-drive"
    case hash
    case headphones
    case heart
    case helpCircle = "help-circle"
    case hexagon
    case home
    case image
    case inbox
    case info
    case instagram
    case italic
    case key
    case layers
    case layout
    case lifeBuoy = "life-buoy"
    case link2 = "link-2"
    case link
    case linkedin
    case list
    case loader
    case lock
    case logIn = "log-in"
    case logOut = "log-out"
    case mail
    case mapPin = "map-pin"
    case map
    case maximize2 = "maximize-2"
    case maximize
    case meh
    case menu
    case messageCircle = "message-circle"
    case messageSquare = "message-square"
    case micOff = "mic-off"
    case mic
    case minimize2 = "minimize-2"
    case minimize
    case minusCircle = "minus-circle"
    case minusSquare = "minus-square"
    case minus
    case monitor
    case moon
    case moreHorizontal = "more-horizontal"
    case moreVertical = "more-vertical"
    case mousePointer = "mouse-pointer"
    case move
    case music
    case navigation2 = "navigation-2"
    case navigation
    case octagon
    case package
    case paperclip
    case pauseCircle = "pause-circle"
    case pause
    case penTool = "pen-tool"
    case percent
    case phoneCall = "phone-call"
    case phoneForwarded = "phone-forwarded"
    case phoneIncoming = "phone-incoming"
    case phoneMissed = "phone-missed"
    case phoneOff = "phone-off"
    case phoneOutgoing = "phone-outgoing"
    case phone
    case pieChart = "pie-chart"
    case playCircle = "play-circle"
    case play
    case plusCircle = "plus-circle"
    case plusSquare = "plus-square"
    case plus
    case pocket
    case power
    case printer
    case radio
    case refreshCcw = "refresh-ccw"
    case refreshCw = "refresh-cw"
    case `repeat`
    case rewind
    case rotateCcw = "rotate-ccw"
    case rotateCw = "rotate-cw"
    case rss
    case save
    case scissors
    case search
    case send
    case server
    case settings
    case share2 = "share-2"
    case share
    case shieldOff = "shield-off"
    case shield
    case shoppingBag = "shopping-bag"
    case shoppingCart = "shopping-cart"
    case shuffle
    case sidebar
    case skipBack = "skip-back"
    case skipForward = "skip-forward"
    case slack
    case slash
    case sliders
    case smartphone
    case smile
    case speaker
    case square
    case star
    case stopCircle = "stop-circle"
    case sun
    case sunrise
    case sunset
    case table
    case tablet
    case tag
    case target
    case terminal
    case thermometer
    case thumbsDown = "thumbs-down"
    case thumbsUp = "thumbs-up"
    case toggleLeft = "toggle-left"
    case toggleRight = "toggle-right"
    case tool
    case trash2 = "trash-2"
    case trash
    case trello
    case trendingDown = "trending-down"
    case trendingUp = "trending-up"
    case triangle
    case truck
    case tv
    case twitch
    case twitter
    case type
    case umbrella
    case underline
    case unlock
    case uploadCloud = "upload-cloud"
    case upload
    case userCheck = "user-check"
    case userMinus = "user-minus"
    case userPlus = "user-plus"
    case userX = "user-x"
    case user
    case users
    case videoOff = "video-off"
    case video
    case voicemail
    case volume1 = "volume-1"
    case volume2 = "volume-2"
    case volumeX = "volume-x"
    case volume
    case watch
    case wifiOff = "wifi-off"
    case wifi
    case wind
    case xCircle = "x-circle"
    case xOctagon = "x-octagon"
    case xSquare = "x-square"
    case x
    case youtube
    case zapOff = "zap-off"
    case zap
    case zoomIn = "zoom-in"
    case zoomOut = "zoom-out"
}
