// AUTO-GENERATED by Scripts/generate.py — DO NOT EDIT.
// Re-run `Scripts/sync-symbols.sh && Scripts/generate.py` to regenerate.

import Foundation
import CornucopiaSymbolsCore

public enum Lucide: String, CornucopiaSymbol, Sendable {

    public static let setName = "Lucide"
    public static let bundle = resolveCornucopiaBundle(
        named: "CornucopiaSymbols_CornucopiaSymbolsLucide",
        fallback: .module
    )

    case aArrowDown = "a-arrow-down"
    case aArrowUp = "a-arrow-up"
    case aLargeSmall = "a-large-small"
    case accessibility
    case activity
    case airVent = "air-vent"
    case airplay
    case alarmClockCheck = "alarm-clock-check"
    case alarmClockMinus = "alarm-clock-minus"
    case alarmClockOff = "alarm-clock-off"
    case alarmClockPlus = "alarm-clock-plus"
    case alarmClock = "alarm-clock"
    case alarmSmoke = "alarm-smoke"
    case album
    case alignCenterHorizontal = "align-center-horizontal"
    case alignCenterVertical = "align-center-vertical"
    case alignCenter = "align-center"
    case alignEndHorizontal = "align-end-horizontal"
    case alignEndVertical = "align-end-vertical"
    case alignHorizontalDistributeCenter = "align-horizontal-distribute-center"
    case alignHorizontalDistributeEnd = "align-horizontal-distribute-end"
    case alignHorizontalDistributeStart = "align-horizontal-distribute-start"
    case alignHorizontalJustifyCenter = "align-horizontal-justify-center"
    case alignHorizontalJustifyEnd = "align-horizontal-justify-end"
    case alignHorizontalJustifyStart = "align-horizontal-justify-start"
    case alignHorizontalSpaceAround = "align-horizontal-space-around"
    case alignHorizontalSpaceBetween = "align-horizontal-space-between"
    case alignJustify = "align-justify"
    case alignLeft = "align-left"
    case alignRight = "align-right"
    case alignStartHorizontal = "align-start-horizontal"
    case alignStartVertical = "align-start-vertical"
    case alignVerticalDistributeCenter = "align-vertical-distribute-center"
    case alignVerticalDistributeEnd = "align-vertical-distribute-end"
    case alignVerticalDistributeStart = "align-vertical-distribute-start"
    case alignVerticalJustifyCenter = "align-vertical-justify-center"
    case alignVerticalJustifyEnd = "align-vertical-justify-end"
    case alignVerticalJustifyStart = "align-vertical-justify-start"
    case alignVerticalSpaceAround = "align-vertical-space-around"
    case alignVerticalSpaceBetween = "align-vertical-space-between"
    case ambulance
    case ampersand
    case ampersands
    case amphora
    case anchor
    case angry
    case annoyed
    case antenna
    case anvil
    case aperture
    case appWindowMac = "app-window-mac"
    case appWindow = "app-window"
    case apple
    case archiveRestore = "archive-restore"
    case archiveX = "archive-x"
    case archive
    case armchair
    case arrowBigDownDash = "arrow-big-down-dash"
    case arrowBigDown = "arrow-big-down"
    case arrowBigLeftDash = "arrow-big-left-dash"
    case arrowBigLeft = "arrow-big-left"
    case arrowBigRightDash = "arrow-big-right-dash"
    case arrowBigRight = "arrow-big-right"
    case arrowBigUpDash = "arrow-big-up-dash"
    case arrowBigUp = "arrow-big-up"
    case arrowDown01 = "arrow-down-0-1"
    case arrowDown10 = "arrow-down-1-0"
    case arrowDownAZ = "arrow-down-a-z"
    case arrowDownFromLine = "arrow-down-from-line"
    case arrowDownLeft = "arrow-down-left"
    case arrowDownNarrowWide = "arrow-down-narrow-wide"
    case arrowDownRight = "arrow-down-right"
    case arrowDownToDot = "arrow-down-to-dot"
    case arrowDownToLine = "arrow-down-to-line"
    case arrowDownUp = "arrow-down-up"
    case arrowDownWideNarrow = "arrow-down-wide-narrow"
    case arrowDownZA = "arrow-down-z-a"
    case arrowDown = "arrow-down"
    case arrowLeftFromLine = "arrow-left-from-line"
    case arrowLeftRight = "arrow-left-right"
    case arrowLeftToLine = "arrow-left-to-line"
    case arrowLeft = "arrow-left"
    case arrowRightFromLine = "arrow-right-from-line"
    case arrowRightLeft = "arrow-right-left"
    case arrowRightToLine = "arrow-right-to-line"
    case arrowRight = "arrow-right"
    case arrowUp01 = "arrow-up-0-1"
    case arrowUp10 = "arrow-up-1-0"
    case arrowUpAZ = "arrow-up-a-z"
    case arrowUpDown = "arrow-up-down"
    case arrowUpFromDot = "arrow-up-from-dot"
    case arrowUpFromLine = "arrow-up-from-line"
    case arrowUpLeft = "arrow-up-left"
    case arrowUpNarrowWide = "arrow-up-narrow-wide"
    case arrowUpRight = "arrow-up-right"
    case arrowUpToLine = "arrow-up-to-line"
    case arrowUpWideNarrow = "arrow-up-wide-narrow"
    case arrowUpZA = "arrow-up-z-a"
    case arrowUp = "arrow-up"
    case arrowsUpFromLine = "arrows-up-from-line"
    case asterisk
    case atSign = "at-sign"
    case atom
    case audioLines = "audio-lines"
    case audioWaveform = "audio-waveform"
    case award
    case axe
    case axis3d = "axis-3d"
    case baby
    case backpack
    case badgeAlert = "badge-alert"
    case badgeCent = "badge-cent"
    case badgeCheck = "badge-check"
    case badgeDollarSign = "badge-dollar-sign"
    case badgeEuro = "badge-euro"
    case badgeHelp = "badge-help"
    case badgeIndianRupee = "badge-indian-rupee"
    case badgeInfo = "badge-info"
    case badgeJapaneseYen = "badge-japanese-yen"
    case badgeMinus = "badge-minus"
    case badgePercent = "badge-percent"
    case badgePlus = "badge-plus"
    case badgePoundSterling = "badge-pound-sterling"
    case badgeRussianRuble = "badge-russian-ruble"
    case badgeSwissFranc = "badge-swiss-franc"
    case badgeX = "badge-x"
    case badge
    case baggageClaim = "baggage-claim"
    case ban
    case banana
    case bandage
    case banknote
    case barcode
    case baseline
    case bath
    case batteryCharging = "battery-charging"
    case batteryFull = "battery-full"
    case batteryLow = "battery-low"
    case batteryMedium = "battery-medium"
    case batteryPlus = "battery-plus"
    case batteryWarning = "battery-warning"
    case battery
    case beaker
    case beanOff = "bean-off"
    case bean
    case bedDouble = "bed-double"
    case bedSingle = "bed-single"
    case bed
    case beef
    case beerOff = "beer-off"
    case beer
    case bellDot = "bell-dot"
    case bellElectric = "bell-electric"
    case bellMinus = "bell-minus"
    case bellOff = "bell-off"
    case bellPlus = "bell-plus"
    case bellRing = "bell-ring"
    case bell
    case betweenHorizontalEnd = "between-horizontal-end"
    case betweenHorizontalStart = "between-horizontal-start"
    case betweenVerticalEnd = "between-vertical-end"
    case betweenVerticalStart = "between-vertical-start"
    case bicepsFlexed = "biceps-flexed"
    case bike
    case binary
    case binoculars
    case biohazard
    case bird
    case bitcoin
    case blend
    case blinds
    case blocks
    case bluetoothConnected = "bluetooth-connected"
    case bluetoothOff = "bluetooth-off"
    case bluetoothSearching = "bluetooth-searching"
    case bluetooth
    case bold
    case bolt
    case bomb
    case bone
    case bookA = "book-a"
    case bookAudio = "book-audio"
    case bookCheck = "book-check"
    case bookCopy = "book-copy"
    case bookDashed = "book-dashed"
    case bookDown = "book-down"
    case bookHeadphones = "book-headphones"
    case bookHeart = "book-heart"
    case bookImage = "book-image"
    case bookKey = "book-key"
    case bookLock = "book-lock"
    case bookMarked = "book-marked"
    case bookMinus = "book-minus"
    case bookOpenCheck = "book-open-check"
    case bookOpenText = "book-open-text"
    case bookOpen = "book-open"
    case bookPlus = "book-plus"
    case bookText = "book-text"
    case bookType = "book-type"
    case bookUp2 = "book-up-2"
    case bookUp = "book-up"
    case bookUser = "book-user"
    case bookX = "book-x"
    case book
    case bookmarkCheck = "bookmark-check"
    case bookmarkMinus = "bookmark-minus"
    case bookmarkPlus = "bookmark-plus"
    case bookmarkX = "bookmark-x"
    case bookmark
    case boomBox = "boom-box"
    case botMessageSquare = "bot-message-square"
    case botOff = "bot-off"
    case bot
    case box
    case boxes
    case braces
    case brackets
    case brainCircuit = "brain-circuit"
    case brainCog = "brain-cog"
    case brain
    case brickWall = "brick-wall"
    case briefcaseBusiness = "briefcase-business"
    case briefcaseConveyorBelt = "briefcase-conveyor-belt"
    case briefcaseMedical = "briefcase-medical"
    case briefcase
    case bringToFront = "bring-to-front"
    case brush
    case bugOff = "bug-off"
    case bugPlay = "bug-play"
    case bug
    case building2 = "building-2"
    case building
    case busFront = "bus-front"
    case bus
    case cableCar = "cable-car"
    case cable
    case cakeSlice = "cake-slice"
    case cake
    case calculator
    case calendar1 = "calendar-1"
    case calendarArrowDown = "calendar-arrow-down"
    case calendarArrowUp = "calendar-arrow-up"
    case calendarCheck2 = "calendar-check-2"
    case calendarCheck = "calendar-check"
    case calendarClock = "calendar-clock"
    case calendarCog = "calendar-cog"
    case calendarDays = "calendar-days"
    case calendarFold = "calendar-fold"
    case calendarHeart = "calendar-heart"
    case calendarMinus2 = "calendar-minus-2"
    case calendarMinus = "calendar-minus"
    case calendarOff = "calendar-off"
    case calendarPlus2 = "calendar-plus-2"
    case calendarPlus = "calendar-plus"
    case calendarRange = "calendar-range"
    case calendarSearch = "calendar-search"
    case calendarSync = "calendar-sync"
    case calendarX2 = "calendar-x-2"
    case calendarX = "calendar-x"
    case calendar
    case cameraOff = "camera-off"
    case camera
    case candyCane = "candy-cane"
    case candyOff = "candy-off"
    case candy
    case cannabis
    case captionsOff = "captions-off"
    case captions
    case carFront = "car-front"
    case carTaxiFront = "car-taxi-front"
    case car
    case caravan
    case carrot
    case caseLower = "case-lower"
    case caseSensitive = "case-sensitive"
    case caseUpper = "case-upper"
    case cassetteTape = "cassette-tape"
    case cast
    case castle
    case cat
    case cctv
    case chartArea = "chart-area"
    case chartBarBig = "chart-bar-big"
    case chartBarDecreasing = "chart-bar-decreasing"
    case chartBarIncreasing = "chart-bar-increasing"
    case chartBarStacked = "chart-bar-stacked"
    case chartBar = "chart-bar"
    case chartCandlestick = "chart-candlestick"
    case chartColumnBig = "chart-column-big"
    case chartColumnDecreasing = "chart-column-decreasing"
    case chartColumnIncreasing = "chart-column-increasing"
    case chartColumnStacked = "chart-column-stacked"
    case chartColumn = "chart-column"
    case chartGantt = "chart-gantt"
    case chartLine = "chart-line"
    case chartNetwork = "chart-network"
    case chartNoAxesColumnDecreasing = "chart-no-axes-column-decreasing"
    case chartNoAxesColumnIncreasing = "chart-no-axes-column-increasing"
    case chartNoAxesColumn = "chart-no-axes-column"
    case chartNoAxesCombined = "chart-no-axes-combined"
    case chartNoAxesGantt = "chart-no-axes-gantt"
    case chartPie = "chart-pie"
    case chartScatter = "chart-scatter"
    case chartSpline = "chart-spline"
    case checkCheck = "check-check"
    case check
    case chefHat = "chef-hat"
    case cherry
    case chevronDown = "chevron-down"
    case chevronFirst = "chevron-first"
    case chevronLast = "chevron-last"
    case chevronLeft = "chevron-left"
    case chevronRight = "chevron-right"
    case chevronUp = "chevron-up"
    case chevronsDownUp = "chevrons-down-up"
    case chevronsDown = "chevrons-down"
    case chevronsLeftRightEllipsis = "chevrons-left-right-ellipsis"
    case chevronsLeftRight = "chevrons-left-right"
    case chevronsLeft = "chevrons-left"
    case chevronsRightLeft = "chevrons-right-left"
    case chevronsRight = "chevrons-right"
    case chevronsUpDown = "chevrons-up-down"
    case chevronsUp = "chevrons-up"
    case chrome
    case church
    case cigaretteOff = "cigarette-off"
    case cigarette
    case circleAlert = "circle-alert"
    case circleArrowDown = "circle-arrow-down"
    case circleArrowLeft = "circle-arrow-left"
    case circleArrowOutDownLeft = "circle-arrow-out-down-left"
    case circleArrowOutDownRight = "circle-arrow-out-down-right"
    case circleArrowOutUpLeft = "circle-arrow-out-up-left"
    case circleArrowOutUpRight = "circle-arrow-out-up-right"
    case circleArrowRight = "circle-arrow-right"
    case circleArrowUp = "circle-arrow-up"
    case circleCheckBig = "circle-check-big"
    case circleCheck = "circle-check"
    case circleChevronDown = "circle-chevron-down"
    case circleChevronLeft = "circle-chevron-left"
    case circleChevronRight = "circle-chevron-right"
    case circleChevronUp = "circle-chevron-up"
    case circleDashed = "circle-dashed"
    case circleDivide = "circle-divide"
    case circleDollarSign = "circle-dollar-sign"
    case circleDotDashed = "circle-dot-dashed"
    case circleDot = "circle-dot"
    case circleEllipsis = "circle-ellipsis"
    case circleEqual = "circle-equal"
    case circleFadingArrowUp = "circle-fading-arrow-up"
    case circleFadingPlus = "circle-fading-plus"
    case circleGauge = "circle-gauge"
    case circleHelp = "circle-help"
    case circleMinus = "circle-minus"
    case circleOff = "circle-off"
    case circleParkingOff = "circle-parking-off"
    case circleParking = "circle-parking"
    case circlePause = "circle-pause"
    case circlePercent = "circle-percent"
    case circlePlay = "circle-play"
    case circlePlus = "circle-plus"
    case circlePower = "circle-power"
    case circleSlash2 = "circle-slash-2"
    case circleSlash = "circle-slash"
    case circleSmall = "circle-small"
    case circleStop = "circle-stop"
    case circleUserRound = "circle-user-round"
    case circleUser = "circle-user"
    case circleX = "circle-x"
    case circle
    case circuitBoard = "circuit-board"
    case citrus
    case clapperboard
    case clipboardCheck = "clipboard-check"
    case clipboardCopy = "clipboard-copy"
    case clipboardList = "clipboard-list"
    case clipboardMinus = "clipboard-minus"
    case clipboardPaste = "clipboard-paste"
    case clipboardPenLine = "clipboard-pen-line"
    case clipboardPen = "clipboard-pen"
    case clipboardPlus = "clipboard-plus"
    case clipboardType = "clipboard-type"
    case clipboardX = "clipboard-x"
    case clipboard
    case clock1 = "clock-1"
    case clock10 = "clock-10"
    case clock11 = "clock-11"
    case clock12 = "clock-12"
    case clock2 = "clock-2"
    case clock3 = "clock-3"
    case clock4 = "clock-4"
    case clock5 = "clock-5"
    case clock6 = "clock-6"
    case clock7 = "clock-7"
    case clock8 = "clock-8"
    case clock9 = "clock-9"
    case clockAlert = "clock-alert"
    case clockArrowDown = "clock-arrow-down"
    case clockArrowUp = "clock-arrow-up"
    case clock
    case cloudAlert = "cloud-alert"
    case cloudCog = "cloud-cog"
    case cloudDownload = "cloud-download"
    case cloudDrizzle = "cloud-drizzle"
    case cloudFog = "cloud-fog"
    case cloudHail = "cloud-hail"
    case cloudLightning = "cloud-lightning"
    case cloudMoonRain = "cloud-moon-rain"
    case cloudMoon = "cloud-moon"
    case cloudOff = "cloud-off"
    case cloudRainWind = "cloud-rain-wind"
    case cloudRain = "cloud-rain"
    case cloudSnow = "cloud-snow"
    case cloudSunRain = "cloud-sun-rain"
    case cloudSun = "cloud-sun"
    case cloudUpload = "cloud-upload"
    case cloud
    case cloudy
    case clover
    case club
    case codeXml = "code-xml"
    case code
    case codepen
    case codesandbox
    case coffee
    case cog
    case coins
    case columns2 = "columns-2"
    case columns3 = "columns-3"
    case columns4 = "columns-4"
    case combine
    case command
    case compass
    case component
    case computer
    case conciergeBell = "concierge-bell"
    case cone
    case construction
    case contactRound = "contact-round"
    case contact
    case container
    case contrast
    case cookie
    case cookingPot = "cooking-pot"
    case copyCheck = "copy-check"
    case copyMinus = "copy-minus"
    case copyPlus = "copy-plus"
    case copySlash = "copy-slash"
    case copyX = "copy-x"
    case copy
    case copyleft
    case copyright
    case cornerDownLeft = "corner-down-left"
    case cornerDownRight = "corner-down-right"
    case cornerLeftDown = "corner-left-down"
    case cornerLeftUp = "corner-left-up"
    case cornerRightDown = "corner-right-down"
    case cornerRightUp = "corner-right-up"
    case cornerUpLeft = "corner-up-left"
    case cornerUpRight = "corner-up-right"
    case cpu
    case creativeCommons = "creative-commons"
    case creditCard = "credit-card"
    case croissant
    case crop
    case cross
    case crosshair
    case crown
    case cuboid
    case cupSoda = "cup-soda"
    case currency
    case cylinder
    case dam
    case databaseBackup = "database-backup"
    case databaseZap = "database-zap"
    case database
    case delete
    case dessert
    case diameter
    case diamondMinus = "diamond-minus"
    case diamondPercent = "diamond-percent"
    case diamondPlus = "diamond-plus"
    case diamond
    case dice1 = "dice-1"
    case dice2 = "dice-2"
    case dice3 = "dice-3"
    case dice4 = "dice-4"
    case dice5 = "dice-5"
    case dice6 = "dice-6"
    case dices
    case diff
    case disc2 = "disc-2"
    case disc3 = "disc-3"
    case discAlbum = "disc-album"
    case disc
    case divide
    case dnaOff = "dna-off"
    case dna
    case dock
    case dog
    case dollarSign = "dollar-sign"
    case donut
    case doorClosed = "door-closed"
    case doorOpen = "door-open"
    case dot
    case download
    case draftingCompass = "drafting-compass"
    case drama
    case dribbble
    case drill
    case dropletOff = "droplet-off"
    case droplet
    case droplets
    case drum
    case drumstick
    case dumbbell
    case earOff = "ear-off"
    case ear
    case earthLock = "earth-lock"
    case earth
    case eclipse
    case eggFried = "egg-fried"
    case eggOff = "egg-off"
    case egg
    case ellipsisVertical = "ellipsis-vertical"
    case ellipsis
    case equalApproximately = "equal-approximately"
    case equalNot = "equal-not"
    case equal
    case eraser
    case ethernetPort = "ethernet-port"
    case euro
    case expand
    case externalLink = "external-link"
    case eyeClosed = "eye-closed"
    case eyeOff = "eye-off"
    case eye
    case facebook
    case factory
    case fan
    case fastForward = "fast-forward"
    case feather
    case fence
    case ferrisWheel = "ferris-wheel"
    case figma
    case fileArchive = "file-archive"
    case fileAudio2 = "file-audio-2"
    case fileAudio = "file-audio"
    case fileAxis3d = "file-axis-3d"
    case fileBadge2 = "file-badge-2"
    case fileBadge = "file-badge"
    case fileBox = "file-box"
    case fileChartColumnIncreasing = "file-chart-column-increasing"
    case fileChartColumn = "file-chart-column"
    case fileChartLine = "file-chart-line"
    case fileChartPie = "file-chart-pie"
    case fileCheck2 = "file-check-2"
    case fileCheck = "file-check"
    case fileClock = "file-clock"
    case fileCode2 = "file-code-2"
    case fileCode = "file-code"
    case fileCog = "file-cog"
    case fileDiff = "file-diff"
    case fileDigit = "file-digit"
    case fileDown = "file-down"
    case fileHeart = "file-heart"
    case fileImage = "file-image"
    case fileInput = "file-input"
    case fileJson2 = "file-json-2"
    case fileJson = "file-json"
    case fileKey2 = "file-key-2"
    case fileKey = "file-key"
    case fileLock2 = "file-lock-2"
    case fileLock = "file-lock"
    case fileMinus2 = "file-minus-2"
    case fileMinus = "file-minus"
    case fileMusic = "file-music"
    case fileOutput = "file-output"
    case filePenLine = "file-pen-line"
    case filePen = "file-pen"
    case filePlus2 = "file-plus-2"
    case filePlus = "file-plus"
    case fileQuestion = "file-question"
    case fileScan = "file-scan"
    case fileSearch2 = "file-search-2"
    case fileSearch = "file-search"
    case fileSliders = "file-sliders"
    case fileSpreadsheet = "file-spreadsheet"
    case fileStack = "file-stack"
    case fileSymlink = "file-symlink"
    case fileTerminal = "file-terminal"
    case fileText = "file-text"
    case fileType2 = "file-type-2"
    case fileType = "file-type"
    case fileUp = "file-up"
    case fileUser = "file-user"
    case fileVideo2 = "file-video-2"
    case fileVideo = "file-video"
    case fileVolume2 = "file-volume-2"
    case fileVolume = "file-volume"
    case fileWarning = "file-warning"
    case fileX2 = "file-x-2"
    case fileX = "file-x"
    case file
    case files
    case film
    case filterX = "filter-x"
    case filter
    case fingerprint
    case fireExtinguisher = "fire-extinguisher"
    case fishOff = "fish-off"
    case fishSymbol = "fish-symbol"
    case fish
    case flagOff = "flag-off"
    case flagTriangleLeft = "flag-triangle-left"
    case flagTriangleRight = "flag-triangle-right"
    case flag
    case flameKindling = "flame-kindling"
    case flame
    case flashlightOff = "flashlight-off"
    case flashlight
    case flaskConicalOff = "flask-conical-off"
    case flaskConical = "flask-conical"
    case flaskRound = "flask-round"
    case flipHorizontal2 = "flip-horizontal-2"
    case flipHorizontal = "flip-horizontal"
    case flipVertical2 = "flip-vertical-2"
    case flipVertical = "flip-vertical"
    case flower2 = "flower-2"
    case flower
    case focus
    case foldHorizontal = "fold-horizontal"
    case foldVertical = "fold-vertical"
    case folderArchive = "folder-archive"
    case folderCheck = "folder-check"
    case folderClock = "folder-clock"
    case folderClosed = "folder-closed"
    case folderCode = "folder-code"
    case folderCog = "folder-cog"
    case folderDot = "folder-dot"
    case folderDown = "folder-down"
    case folderGit2 = "folder-git-2"
    case folderGit = "folder-git"
    case folderHeart = "folder-heart"
    case folderInput = "folder-input"
    case folderKanban = "folder-kanban"
    case folderKey = "folder-key"
    case folderLock = "folder-lock"
    case folderMinus = "folder-minus"
    case folderOpenDot = "folder-open-dot"
    case folderOpen = "folder-open"
    case folderOutput = "folder-output"
    case folderPen = "folder-pen"
    case folderPlus = "folder-plus"
    case folderRoot = "folder-root"
    case folderSearch2 = "folder-search-2"
    case folderSearch = "folder-search"
    case folderSymlink = "folder-symlink"
    case folderSync = "folder-sync"
    case folderTree = "folder-tree"
    case folderUp = "folder-up"
    case folderX = "folder-x"
    case folder
    case folders
    case footprints
    case forklift
    case forward
    case frame
    case framer
    case frown
    case fuel
    case fullscreen
    case galleryHorizontalEnd = "gallery-horizontal-end"
    case galleryHorizontal = "gallery-horizontal"
    case galleryThumbnails = "gallery-thumbnails"
    case galleryVerticalEnd = "gallery-vertical-end"
    case galleryVertical = "gallery-vertical"
    case gamepad2 = "gamepad-2"
    case gamepad
    case gauge
    case gavel
    case gem
    case ghost
    case gift
    case gitBranchPlus = "git-branch-plus"
    case gitBranch = "git-branch"
    case gitCommitHorizontal = "git-commit-horizontal"
    case gitCommitVertical = "git-commit-vertical"
    case gitCompareArrows = "git-compare-arrows"
    case gitCompare = "git-compare"
    case gitFork = "git-fork"
    case gitGraph = "git-graph"
    case gitMerge = "git-merge"
    case gitPullRequestArrow = "git-pull-request-arrow"
    case gitPullRequestClosed = "git-pull-request-closed"
    case gitPullRequestCreateArrow = "git-pull-request-create-arrow"
    case gitPullRequestCreate = "git-pull-request-create"
    case gitPullRequestDraft = "git-pull-request-draft"
    case gitPullRequest = "git-pull-request"
    case github
    case gitlab
    case glassWater = "glass-water"
    case glasses
    case globeLock = "globe-lock"
    case globe
    case goal
    case grab
    case graduationCap = "graduation-cap"
    case grape
    case grid2x2Check = "grid-2x2-check"
    case grid2x2Plus = "grid-2x2-plus"
    case grid2x2X = "grid-2x2-x"
    case grid2x2 = "grid-2x2"
    case grid3x3 = "grid-3x3"
    case gripHorizontal = "grip-horizontal"
    case gripVertical = "grip-vertical"
    case grip
    case group
    case guitar
    case ham
    case hammer
    case handCoins = "hand-coins"
    case handHeart = "hand-heart"
    case handHelping = "hand-helping"
    case handMetal = "hand-metal"
    case handPlatter = "hand-platter"
    case hand
    case handshake
    case hardDriveDownload = "hard-drive-download"
    case hardDriveUpload = "hard-drive-upload"
    case hardDrive = "hard-drive"
    case hardHat = "hard-hat"
    case hash
    case haze
    case hdmiPort = "hdmi-port"
    case heading1 = "heading-1"
    case heading2 = "heading-2"
    case heading3 = "heading-3"
    case heading4 = "heading-4"
    case heading5 = "heading-5"
    case heading6 = "heading-6"
    case heading
    case headphoneOff = "headphone-off"
    case headphones
    case headset
    case heartCrack = "heart-crack"
    case heartHandshake = "heart-handshake"
    case heartOff = "heart-off"
    case heartPulse = "heart-pulse"
    case heart
    case heater
    case hexagon
    case highlighter
    case history
    case hopOff = "hop-off"
    case hop
    case hospital
    case hotel
    case hourglass
    case housePlug = "house-plug"
    case housePlus = "house-plus"
    case houseWifi = "house-wifi"
    case house
    case iceCreamBowl = "ice-cream-bowl"
    case iceCreamCone = "ice-cream-cone"
    case idCard = "id-card"
    case imageDown = "image-down"
    case imageMinus = "image-minus"
    case imageOff = "image-off"
    case imagePlay = "image-play"
    case imagePlus = "image-plus"
    case imageUp = "image-up"
    case imageUpscale = "image-upscale"
    case image
    case images
    case `import`
    case inbox
    case indentDecrease = "indent-decrease"
    case indentIncrease = "indent-increase"
    case indianRupee = "indian-rupee"
    case infinity
    case info
    case inspectionPanel = "inspection-panel"
    case instagram
    case italic
    case iterationCcw = "iteration-ccw"
    case iterationCw = "iteration-cw"
    case japaneseYen = "japanese-yen"
    case joystick
    case kanban
    case keyRound = "key-round"
    case keySquare = "key-square"
    case key
    case keyboardMusic = "keyboard-music"
    case keyboardOff = "keyboard-off"
    case keyboard
    case lampCeiling = "lamp-ceiling"
    case lampDesk = "lamp-desk"
    case lampFloor = "lamp-floor"
    case lampWallDown = "lamp-wall-down"
    case lampWallUp = "lamp-wall-up"
    case lamp
    case landPlot = "land-plot"
    case landmark
    case languages
    case laptopMinimalCheck = "laptop-minimal-check"
    case laptopMinimal = "laptop-minimal"
    case laptop
    case lassoSelect = "lasso-select"
    case lasso
    case laugh
    case layers2 = "layers-2"
    case layers
    case layoutDashboard = "layout-dashboard"
    case layoutGrid = "layout-grid"
    case layoutList = "layout-list"
    case layoutPanelLeft = "layout-panel-left"
    case layoutPanelTop = "layout-panel-top"
    case layoutTemplate = "layout-template"
    case leaf
    case leafyGreen = "leafy-green"
    case lectern
    case letterText = "letter-text"
    case libraryBig = "library-big"
    case library
    case lifeBuoy = "life-buoy"
    case ligature
    case lightbulbOff = "lightbulb-off"
    case lightbulb
    case link2Off = "link-2-off"
    case link2 = "link-2"
    case link
    case linkedin
    case listCheck = "list-check"
    case listChecks = "list-checks"
    case listCollapse = "list-collapse"
    case listEnd = "list-end"
    case listFilterPlus = "list-filter-plus"
    case listFilter = "list-filter"
    case listMinus = "list-minus"
    case listMusic = "list-music"
    case listOrdered = "list-ordered"
    case listPlus = "list-plus"
    case listRestart = "list-restart"
    case listStart = "list-start"
    case listTodo = "list-todo"
    case listTree = "list-tree"
    case listVideo = "list-video"
    case listX = "list-x"
    case list
    case loaderCircle = "loader-circle"
    case loaderPinwheel = "loader-pinwheel"
    case loader
    case locateFixed = "locate-fixed"
    case locateOff = "locate-off"
    case locate
    case lockKeyholeOpen = "lock-keyhole-open"
    case lockKeyhole = "lock-keyhole"
    case lockOpen = "lock-open"
    case lock
    case logIn = "log-in"
    case logOut = "log-out"
    case logs
    case lollipop
    case luggage
    case magnet
    case mailCheck = "mail-check"
    case mailMinus = "mail-minus"
    case mailOpen = "mail-open"
    case mailPlus = "mail-plus"
    case mailQuestion = "mail-question"
    case mailSearch = "mail-search"
    case mailWarning = "mail-warning"
    case mailX = "mail-x"
    case mail
    case mailbox
    case mails
    case mapPinCheckInside = "map-pin-check-inside"
    case mapPinCheck = "map-pin-check"
    case mapPinHouse = "map-pin-house"
    case mapPinMinusInside = "map-pin-minus-inside"
    case mapPinMinus = "map-pin-minus"
    case mapPinOff = "map-pin-off"
    case mapPinPlusInside = "map-pin-plus-inside"
    case mapPinPlus = "map-pin-plus"
    case mapPinXInside = "map-pin-x-inside"
    case mapPinX = "map-pin-x"
    case mapPin = "map-pin"
    case mapPinned = "map-pinned"
    case mapPlus = "map-plus"
    case map
    case marsStroke = "mars-stroke"
    case mars
    case martini
    case maximize2 = "maximize-2"
    case maximize
    case medal
    case megaphoneOff = "megaphone-off"
    case megaphone
    case meh
    case memoryStick = "memory-stick"
    case menu
    case merge
    case messageCircleCode = "message-circle-code"
    case messageCircleDashed = "message-circle-dashed"
    case messageCircleHeart = "message-circle-heart"
    case messageCircleMore = "message-circle-more"
    case messageCircleOff = "message-circle-off"
    case messageCirclePlus = "message-circle-plus"
    case messageCircleQuestion = "message-circle-question"
    case messageCircleReply = "message-circle-reply"
    case messageCircleWarning = "message-circle-warning"
    case messageCircleX = "message-circle-x"
    case messageCircle = "message-circle"
    case messageSquareCode = "message-square-code"
    case messageSquareDashed = "message-square-dashed"
    case messageSquareDiff = "message-square-diff"
    case messageSquareDot = "message-square-dot"
    case messageSquareHeart = "message-square-heart"
    case messageSquareLock = "message-square-lock"
    case messageSquareMore = "message-square-more"
    case messageSquareOff = "message-square-off"
    case messageSquarePlus = "message-square-plus"
    case messageSquareQuote = "message-square-quote"
    case messageSquareReply = "message-square-reply"
    case messageSquareShare = "message-square-share"
    case messageSquareText = "message-square-text"
    case messageSquareWarning = "message-square-warning"
    case messageSquareX = "message-square-x"
    case messageSquare = "message-square"
    case messagesSquare = "messages-square"
    case micOff = "mic-off"
    case micVocal = "mic-vocal"
    case mic
    case microchip
    case microscope
    case microwave
    case milestone
    case milkOff = "milk-off"
    case milk
    case minimize2 = "minimize-2"
    case minimize
    case minus
    case monitorCheck = "monitor-check"
    case monitorCog = "monitor-cog"
    case monitorDot = "monitor-dot"
    case monitorDown = "monitor-down"
    case monitorOff = "monitor-off"
    case monitorPause = "monitor-pause"
    case monitorPlay = "monitor-play"
    case monitorSmartphone = "monitor-smartphone"
    case monitorSpeaker = "monitor-speaker"
    case monitorStop = "monitor-stop"
    case monitorUp = "monitor-up"
    case monitorX = "monitor-x"
    case monitor
    case moonStar = "moon-star"
    case moon
    case mountainSnow = "mountain-snow"
    case mountain
    case mouseOff = "mouse-off"
    case mousePointer2 = "mouse-pointer-2"
    case mousePointerBan = "mouse-pointer-ban"
    case mousePointerClick = "mouse-pointer-click"
    case mousePointer = "mouse-pointer"
    case mouse
    case move3d = "move-3d"
    case moveDiagonal2 = "move-diagonal-2"
    case moveDiagonal = "move-diagonal"
    case moveDownLeft = "move-down-left"
    case moveDownRight = "move-down-right"
    case moveDown = "move-down"
    case moveHorizontal = "move-horizontal"
    case moveLeft = "move-left"
    case moveRight = "move-right"
    case moveUpLeft = "move-up-left"
    case moveUpRight = "move-up-right"
    case moveUp = "move-up"
    case moveVertical = "move-vertical"
    case move
    case music2 = "music-2"
    case music3 = "music-3"
    case music4 = "music-4"
    case music
    case navigation2Off = "navigation-2-off"
    case navigation2 = "navigation-2"
    case navigationOff = "navigation-off"
    case navigation
    case network
    case newspaper
    case nfc
    case nonBinary = "non-binary"
    case notebookPen = "notebook-pen"
    case notebookTabs = "notebook-tabs"
    case notebookText = "notebook-text"
    case notebook
    case notepadTextDashed = "notepad-text-dashed"
    case notepadText = "notepad-text"
    case nutOff = "nut-off"
    case nut
    case octagonAlert = "octagon-alert"
    case octagonMinus = "octagon-minus"
    case octagonPause = "octagon-pause"
    case octagonX = "octagon-x"
    case octagon
    case omega
    case option
    case orbit
    case origami
    case package2 = "package-2"
    case packageCheck = "package-check"
    case packageMinus = "package-minus"
    case packageOpen = "package-open"
    case packagePlus = "package-plus"
    case packageSearch = "package-search"
    case packageX = "package-x"
    case package
    case paintBucket = "paint-bucket"
    case paintRoller = "paint-roller"
    case paintbrushVertical = "paintbrush-vertical"
    case paintbrush
    case palette
    case panelBottomClose = "panel-bottom-close"
    case panelBottomDashed = "panel-bottom-dashed"
    case panelBottomOpen = "panel-bottom-open"
    case panelBottom = "panel-bottom"
    case panelLeftClose = "panel-left-close"
    case panelLeftDashed = "panel-left-dashed"
    case panelLeftOpen = "panel-left-open"
    case panelLeft = "panel-left"
    case panelRightClose = "panel-right-close"
    case panelRightDashed = "panel-right-dashed"
    case panelRightOpen = "panel-right-open"
    case panelRight = "panel-right"
    case panelTopClose = "panel-top-close"
    case panelTopDashed = "panel-top-dashed"
    case panelTopOpen = "panel-top-open"
    case panelTop = "panel-top"
    case panelsLeftBottom = "panels-left-bottom"
    case panelsRightBottom = "panels-right-bottom"
    case panelsTopLeft = "panels-top-left"
    case paperclip
    case parentheses
    case parkingMeter = "parking-meter"
    case partyPopper = "party-popper"
    case pause
    case pawPrint = "paw-print"
    case pcCase = "pc-case"
    case penLine = "pen-line"
    case penOff = "pen-off"
    case penTool = "pen-tool"
    case pen
    case pencilLine = "pencil-line"
    case pencilOff = "pencil-off"
    case pencilRuler = "pencil-ruler"
    case pencil
    case pentagon
    case percent
    case personStanding = "person-standing"
    case philippinePeso = "philippine-peso"
    case phoneCall = "phone-call"
    case phoneForwarded = "phone-forwarded"
    case phoneIncoming = "phone-incoming"
    case phoneMissed = "phone-missed"
    case phoneOff = "phone-off"
    case phoneOutgoing = "phone-outgoing"
    case phone
    case pi
    case piano
    case pickaxe
    case pictureInPicture2 = "picture-in-picture-2"
    case pictureInPicture = "picture-in-picture"
    case piggyBank = "piggy-bank"
    case pilcrowLeft = "pilcrow-left"
    case pilcrowRight = "pilcrow-right"
    case pilcrow
    case pillBottle = "pill-bottle"
    case pill
    case pinOff = "pin-off"
    case pin
    case pipette
    case pizza
    case planeLanding = "plane-landing"
    case planeTakeoff = "plane-takeoff"
    case plane
    case play
    case plug2 = "plug-2"
    case plugZap = "plug-zap"
    case plug
    case plus
    case pocketKnife = "pocket-knife"
    case pocket
    case podcast
    case pointerOff = "pointer-off"
    case pointer
    case popcorn
    case popsicle
    case poundSterling = "pound-sterling"
    case powerOff = "power-off"
    case power
    case presentation
    case printerCheck = "printer-check"
    case printer
    case projector
    case proportions
    case puzzle
    case pyramid
    case qrCode = "qr-code"
    case quote
    case rabbit
    case radar
    case radiation
    case radical
    case radioReceiver = "radio-receiver"
    case radioTower = "radio-tower"
    case radio
    case radius
    case railSymbol = "rail-symbol"
    case rainbow
    case rat
    case ratio
    case receiptCent = "receipt-cent"
    case receiptEuro = "receipt-euro"
    case receiptIndianRupee = "receipt-indian-rupee"
    case receiptJapaneseYen = "receipt-japanese-yen"
    case receiptPoundSterling = "receipt-pound-sterling"
    case receiptRussianRuble = "receipt-russian-ruble"
    case receiptSwissFranc = "receipt-swiss-franc"
    case receiptText = "receipt-text"
    case receipt
    case rectangleEllipsis = "rectangle-ellipsis"
    case rectangleHorizontal = "rectangle-horizontal"
    case rectangleVertical = "rectangle-vertical"
    case recycle
    case redo2 = "redo-2"
    case redoDot = "redo-dot"
    case redo
    case refreshCcwDot = "refresh-ccw-dot"
    case refreshCcw = "refresh-ccw"
    case refreshCwOff = "refresh-cw-off"
    case refreshCw = "refresh-cw"
    case refrigerator
    case regex
    case removeFormatting = "remove-formatting"
    case repeat1 = "repeat-1"
    case repeat2 = "repeat-2"
    case `repeat`
    case replaceAll = "replace-all"
    case replace
    case replyAll = "reply-all"
    case reply
    case rewind
    case ribbon
    case rocket
    case rockingChair = "rocking-chair"
    case rollerCoaster = "roller-coaster"
    case rotate3d = "rotate-3d"
    case rotateCcwSquare = "rotate-ccw-square"
    case rotateCcw = "rotate-ccw"
    case rotateCwSquare = "rotate-cw-square"
    case rotateCw = "rotate-cw"
    case routeOff = "route-off"
    case route
    case router
    case rows2 = "rows-2"
    case rows3 = "rows-3"
    case rows4 = "rows-4"
    case rss
    case ruler
    case russianRuble = "russian-ruble"
    case sailboat
    case salad
    case sandwich
    case satelliteDish = "satellite-dish"
    case satellite
    case saveAll = "save-all"
    case saveOff = "save-off"
    case save
    case scale3d = "scale-3d"
    case scale
    case scaling
    case scanBarcode = "scan-barcode"
    case scanEye = "scan-eye"
    case scanFace = "scan-face"
    case scanHeart = "scan-heart"
    case scanLine = "scan-line"
    case scanQrCode = "scan-qr-code"
    case scanSearch = "scan-search"
    case scanText = "scan-text"
    case scan
    case school
    case scissorsLineDashed = "scissors-line-dashed"
    case scissors
    case screenShareOff = "screen-share-off"
    case screenShare = "screen-share"
    case scrollText = "scroll-text"
    case scroll
    case searchCheck = "search-check"
    case searchCode = "search-code"
    case searchSlash = "search-slash"
    case searchX = "search-x"
    case search
    case section
    case sendHorizontal = "send-horizontal"
    case sendToBack = "send-to-back"
    case send
    case separatorHorizontal = "separator-horizontal"
    case separatorVertical = "separator-vertical"
    case serverCog = "server-cog"
    case serverCrash = "server-crash"
    case serverOff = "server-off"
    case server
    case settings2 = "settings-2"
    case settings
    case shapes
    case share2 = "share-2"
    case share
    case sheet
    case shell
    case shieldAlert = "shield-alert"
    case shieldBan = "shield-ban"
    case shieldCheck = "shield-check"
    case shieldEllipsis = "shield-ellipsis"
    case shieldHalf = "shield-half"
    case shieldMinus = "shield-minus"
    case shieldOff = "shield-off"
    case shieldPlus = "shield-plus"
    case shieldQuestion = "shield-question"
    case shieldUser = "shield-user"
    case shieldX = "shield-x"
    case shield
    case shipWheel = "ship-wheel"
    case ship
    case shirt
    case shoppingBag = "shopping-bag"
    case shoppingBasket = "shopping-basket"
    case shoppingCart = "shopping-cart"
    case shovel
    case showerHead = "shower-head"
    case shrink
    case shrub
    case shuffle
    case sigma
    case signalHigh = "signal-high"
    case signalLow = "signal-low"
    case signalMedium = "signal-medium"
    case signalZero = "signal-zero"
    case signal
    case signature
    case signpostBig = "signpost-big"
    case signpost
    case siren
    case skipBack = "skip-back"
    case skipForward = "skip-forward"
    case skull
    case slack
    case slash
    case slice
    case slidersHorizontal = "sliders-horizontal"
    case slidersVertical = "sliders-vertical"
    case smartphoneCharging = "smartphone-charging"
    case smartphoneNfc = "smartphone-nfc"
    case smartphone
    case smilePlus = "smile-plus"
    case smile
    case snail
    case snowflake
    case sofa
    case soup
    case space
    case spade
    case sparkle
    case sparkles
    case speaker
    case speech
    case spellCheck2 = "spell-check-2"
    case spellCheck = "spell-check"
    case spline
    case split
    case sprayCan = "spray-can"
    case sprout
    case squareActivity = "square-activity"
    case squareArrowDownLeft = "square-arrow-down-left"
    case squareArrowDownRight = "square-arrow-down-right"
    case squareArrowDown = "square-arrow-down"
    case squareArrowLeft = "square-arrow-left"
    case squareArrowOutDownLeft = "square-arrow-out-down-left"
    case squareArrowOutDownRight = "square-arrow-out-down-right"
    case squareArrowOutUpLeft = "square-arrow-out-up-left"
    case squareArrowOutUpRight = "square-arrow-out-up-right"
    case squareArrowRight = "square-arrow-right"
    case squareArrowUpLeft = "square-arrow-up-left"
    case squareArrowUpRight = "square-arrow-up-right"
    case squareArrowUp = "square-arrow-up"
    case squareAsterisk = "square-asterisk"
    case squareBottomDashedScissors = "square-bottom-dashed-scissors"
    case squareChartGantt = "square-chart-gantt"
    case squareCheckBig = "square-check-big"
    case squareCheck = "square-check"
    case squareChevronDown = "square-chevron-down"
    case squareChevronLeft = "square-chevron-left"
    case squareChevronRight = "square-chevron-right"
    case squareChevronUp = "square-chevron-up"
    case squareCode = "square-code"
    case squareDashedBottomCode = "square-dashed-bottom-code"
    case squareDashedBottom = "square-dashed-bottom"
    case squareDashedKanban = "square-dashed-kanban"
    case squareDashedMousePointer = "square-dashed-mouse-pointer"
    case squareDashed = "square-dashed"
    case squareDivide = "square-divide"
    case squareDot = "square-dot"
    case squareEqual = "square-equal"
    case squareFunction = "square-function"
    case squareKanban = "square-kanban"
    case squareLibrary = "square-library"
    case squareM = "square-m"
    case squareMenu = "square-menu"
    case squareMinus = "square-minus"
    case squareMousePointer = "square-mouse-pointer"
    case squareParkingOff = "square-parking-off"
    case squareParking = "square-parking"
    case squarePen = "square-pen"
    case squarePercent = "square-percent"
    case squarePi = "square-pi"
    case squarePilcrow = "square-pilcrow"
    case squarePlay = "square-play"
    case squarePlus = "square-plus"
    case squarePower = "square-power"
    case squareRadical = "square-radical"
    case squareRoundCorner = "square-round-corner"
    case squareScissors = "square-scissors"
    case squareSigma = "square-sigma"
    case squareSlash = "square-slash"
    case squareSplitHorizontal = "square-split-horizontal"
    case squareSplitVertical = "square-split-vertical"
    case squareSquare = "square-square"
    case squareStack = "square-stack"
    case squareTerminal = "square-terminal"
    case squareUserRound = "square-user-round"
    case squareUser = "square-user"
    case squareX = "square-x"
    case square
    case squircle
    case squirrel
    case stamp
    case starHalf = "star-half"
    case starOff = "star-off"
    case star
    case stepBack = "step-back"
    case stepForward = "step-forward"
    case stethoscope
    case sticker
    case stickyNote = "sticky-note"
    case store
    case stretchHorizontal = "stretch-horizontal"
    case stretchVertical = "stretch-vertical"
    case strikethrough
    case `subscript`
    case sunDim = "sun-dim"
    case sunMedium = "sun-medium"
    case sunMoon = "sun-moon"
    case sunSnow = "sun-snow"
    case sun
    case sunrise
    case sunset
    case superscript
    case swatchBook = "swatch-book"
    case swissFranc = "swiss-franc"
    case switchCamera = "switch-camera"
    case sword
    case swords
    case syringe
    case table2 = "table-2"
    case tableCellsMerge = "table-cells-merge"
    case tableCellsSplit = "table-cells-split"
    case tableColumnsSplit = "table-columns-split"
    case tableOfContents = "table-of-contents"
    case tableProperties = "table-properties"
    case tableRowsSplit = "table-rows-split"
    case table
    case tabletSmartphone = "tablet-smartphone"
    case tablet
    case tablets
    case tag
    case tags
    case tally1 = "tally-1"
    case tally2 = "tally-2"
    case tally3 = "tally-3"
    case tally4 = "tally-4"
    case tally5 = "tally-5"
    case tangent
    case target
    case telescope
    case tentTree = "tent-tree"
    case tent
    case terminal
    case testTubeDiagonal = "test-tube-diagonal"
    case testTube = "test-tube"
    case testTubes = "test-tubes"
    case textCursorInput = "text-cursor-input"
    case textCursor = "text-cursor"
    case textQuote = "text-quote"
    case textSearch = "text-search"
    case textSelect = "text-select"
    case text
    case theater
    case thermometerSnowflake = "thermometer-snowflake"
    case thermometerSun = "thermometer-sun"
    case thermometer
    case thumbsDown = "thumbs-down"
    case thumbsUp = "thumbs-up"
    case ticketCheck = "ticket-check"
    case ticketMinus = "ticket-minus"
    case ticketPercent = "ticket-percent"
    case ticketPlus = "ticket-plus"
    case ticketSlash = "ticket-slash"
    case ticketX = "ticket-x"
    case ticket
    case ticketsPlane = "tickets-plane"
    case tickets
    case timerOff = "timer-off"
    case timerReset = "timer-reset"
    case timer
    case toggleLeft = "toggle-left"
    case toggleRight = "toggle-right"
    case toilet
    case tornado
    case torus
    case touchpadOff = "touchpad-off"
    case touchpad
    case towerControl = "tower-control"
    case toyBrick = "toy-brick"
    case tractor
    case trafficCone = "traffic-cone"
    case trainFrontTunnel = "train-front-tunnel"
    case trainFront = "train-front"
    case trainTrack = "train-track"
    case tramFront = "tram-front"
    case transgender
    case trash2 = "trash-2"
    case trash
    case treeDeciduous = "tree-deciduous"
    case treePalm = "tree-palm"
    case treePine = "tree-pine"
    case trees
    case trello
    case trendingDown = "trending-down"
    case trendingUpDown = "trending-up-down"
    case trendingUp = "trending-up"
    case triangleAlert = "triangle-alert"
    case triangleDashed = "triangle-dashed"
    case triangleRight = "triangle-right"
    case triangle
    case trophy
    case truck
    case turtle
    case tvMinimalPlay = "tv-minimal-play"
    case tvMinimal = "tv-minimal"
    case tv
    case twitch
    case twitter
    case typeOutline = "type-outline"
    case type
    case umbrellaOff = "umbrella-off"
    case umbrella
    case underline
    case undo2 = "undo-2"
    case undoDot = "undo-dot"
    case undo
    case unfoldHorizontal = "unfold-horizontal"
    case unfoldVertical = "unfold-vertical"
    case ungroup
    case university
    case unlink2 = "unlink-2"
    case unlink
    case unplug
    case upload
    case usb
    case userCheck = "user-check"
    case userCog = "user-cog"
    case userMinus = "user-minus"
    case userPen = "user-pen"
    case userPlus = "user-plus"
    case userRoundCheck = "user-round-check"
    case userRoundCog = "user-round-cog"
    case userRoundMinus = "user-round-minus"
    case userRoundPen = "user-round-pen"
    case userRoundPlus = "user-round-plus"
    case userRoundSearch = "user-round-search"
    case userRoundX = "user-round-x"
    case userRound = "user-round"
    case userSearch = "user-search"
    case userX = "user-x"
    case user
    case usersRound = "users-round"
    case users
    case utensilsCrossed = "utensils-crossed"
    case utensils
    case utilityPole = "utility-pole"
    case variable
    case vault
    case vegan
    case venetianMask = "venetian-mask"
    case venusAndMars = "venus-and-mars"
    case venus
    case vibrateOff = "vibrate-off"
    case vibrate
    case videoOff = "video-off"
    case video
    case videotape
    case view
    case voicemail
    case volleyball
    case volume1 = "volume-1"
    case volume2 = "volume-2"
    case volumeOff = "volume-off"
    case volumeX = "volume-x"
    case volume
    case vote
    case walletCards = "wallet-cards"
    case walletMinimal = "wallet-minimal"
    case wallet
    case wallpaper
    case wandSparkles = "wand-sparkles"
    case wand
    case warehouse
    case washingMachine = "washing-machine"
    case watch
    case wavesLadder = "waves-ladder"
    case waves
    case waypoints
    case webcam
    case webhookOff = "webhook-off"
    case webhook
    case weight
    case wheatOff = "wheat-off"
    case wheat
    case wholeWord = "whole-word"
    case wifiHigh = "wifi-high"
    case wifiLow = "wifi-low"
    case wifiOff = "wifi-off"
    case wifiZero = "wifi-zero"
    case wifi
    case windArrowDown = "wind-arrow-down"
    case wind
    case wineOff = "wine-off"
    case wine
    case workflow
    case worm
    case wrapText = "wrap-text"
    case wrench
    case x
    case youtube
    case zapOff = "zap-off"
    case zap
    case zoomIn = "zoom-in"
    case zoomOut = "zoom-out"
}
