// AUTO-GENERATED by Scripts/generate.py — DO NOT EDIT.
// Re-run `Scripts/sync-symbols.sh && Scripts/generate.py` to regenerate.

import Foundation
import CornucopiaSymbolsCore

public enum FontAwesome: String, CornucopiaSymbol, Sendable {

    public static let setName = "FontAwesome"
    public static let bundle = resolveCornucopiaBundle(
        named: "CornucopiaSymbols_CornucopiaSymbolsFontAwesome",
        fallback: .module
    )

    case _0 = "0"
    case _1 = "1"
    case _2 = "2"
    case _3 = "3"
    case _4 = "4"
    case _42Group = "42-group"
    case _5 = "5"
    case _500px = "500px"
    case _6 = "6"
    case _7 = "7"
    case _8 = "8"
    case _9 = "9"
    case a
    case accessibleIcon = "accessible-icon"
    case accusoft
    case addressBookFill = "address-book.fill"
    case addressBook = "address-book"
    case addressCardFill = "address-card.fill"
    case addressCard = "address-card"
    case adn
    case adversal
    case affiliatetheme
    case airbnb
    case algolia
    case alignCenter = "align-center"
    case alignJustify = "align-justify"
    case alignLeft = "align-left"
    case alignRight = "align-right"
    case alipay
    case amazonPay = "amazon-pay"
    case amazon
    case amilia
    case anchorCircleCheck = "anchor-circle-check"
    case anchorCircleExclamation = "anchor-circle-exclamation"
    case anchorCircleXmark = "anchor-circle-xmark"
    case anchorLock = "anchor-lock"
    case anchor
    case android
    case angellist
    case angleDown = "angle-down"
    case angleLeft = "angle-left"
    case angleRight = "angle-right"
    case angleUp = "angle-up"
    case anglesDown = "angles-down"
    case anglesLeft = "angles-left"
    case anglesRight = "angles-right"
    case anglesUp = "angles-up"
    case angrycreative
    case angular
    case ankh
    case appStoreIos = "app-store-ios"
    case appStore = "app-store"
    case apper
    case applePay = "apple-pay"
    case appleWhole = "apple-whole"
    case apple
    case archway
    case arrowDown19 = "arrow-down-1-9"
    case arrowDown91 = "arrow-down-9-1"
    case arrowDownAZ = "arrow-down-a-z"
    case arrowDownLong = "arrow-down-long"
    case arrowDownShortWide = "arrow-down-short-wide"
    case arrowDownUpAcrossLine = "arrow-down-up-across-line"
    case arrowDownUpLock = "arrow-down-up-lock"
    case arrowDownWideShort = "arrow-down-wide-short"
    case arrowDownZA = "arrow-down-z-a"
    case arrowDown = "arrow-down"
    case arrowLeftLong = "arrow-left-long"
    case arrowLeft = "arrow-left"
    case arrowPointer = "arrow-pointer"
    case arrowRightArrowLeft = "arrow-right-arrow-left"
    case arrowRightFromBracket = "arrow-right-from-bracket"
    case arrowRightLong = "arrow-right-long"
    case arrowRightToBracket = "arrow-right-to-bracket"
    case arrowRightToCity = "arrow-right-to-city"
    case arrowRight = "arrow-right"
    case arrowRotateLeft = "arrow-rotate-left"
    case arrowRotateRight = "arrow-rotate-right"
    case arrowTrendDown = "arrow-trend-down"
    case arrowTrendUp = "arrow-trend-up"
    case arrowTurnDown = "arrow-turn-down"
    case arrowTurnUp = "arrow-turn-up"
    case arrowUp19 = "arrow-up-1-9"
    case arrowUp91 = "arrow-up-9-1"
    case arrowUpAZ = "arrow-up-a-z"
    case arrowUpFromBracket = "arrow-up-from-bracket"
    case arrowUpFromGroundWater = "arrow-up-from-ground-water"
    case arrowUpFromWaterPump = "arrow-up-from-water-pump"
    case arrowUpLong = "arrow-up-long"
    case arrowUpRightDots = "arrow-up-right-dots"
    case arrowUpRightFromSquare = "arrow-up-right-from-square"
    case arrowUpShortWide = "arrow-up-short-wide"
    case arrowUpWideShort = "arrow-up-wide-short"
    case arrowUpZA = "arrow-up-z-a"
    case arrowUp = "arrow-up"
    case arrowsDownToLine = "arrows-down-to-line"
    case arrowsDownToPeople = "arrows-down-to-people"
    case arrowsLeftRightToLine = "arrows-left-right-to-line"
    case arrowsLeftRight = "arrows-left-right"
    case arrowsRotate = "arrows-rotate"
    case arrowsSpin = "arrows-spin"
    case arrowsSplitUpAndLeft = "arrows-split-up-and-left"
    case arrowsToCircle = "arrows-to-circle"
    case arrowsToDot = "arrows-to-dot"
    case arrowsToEye = "arrows-to-eye"
    case arrowsTurnRight = "arrows-turn-right"
    case arrowsTurnToDots = "arrows-turn-to-dots"
    case arrowsUpDownLeftRight = "arrows-up-down-left-right"
    case arrowsUpDown = "arrows-up-down"
    case arrowsUpToLine = "arrows-up-to-line"
    case artstation
    case asterisk
    case asymmetrik
    case at
    case atlassian
    case atom
    case audible
    case audioDescription = "audio-description"
    case australSign = "austral-sign"
    case autoprefixer
    case avianex
    case aviato
    case award
    case aws
    case b
    case babyCarriage = "baby-carriage"
    case baby
    case backwardFast = "backward-fast"
    case backwardStep = "backward-step"
    case backward
    case bacon
    case bacteria
    case bacterium
    case bagShopping = "bag-shopping"
    case bahai
    case bahtSign = "baht-sign"
    case banSmoking = "ban-smoking"
    case ban
    case bandage
    case bandcamp
    case bangladeshiTakaSign = "bangladeshi-taka-sign"
    case barcode
    case barsProgress = "bars-progress"
    case barsStaggered = "bars-staggered"
    case bars
    case baseballBatBall = "baseball-bat-ball"
    case baseball
    case basketShopping = "basket-shopping"
    case basketball
    case bath
    case batteryEmpty = "battery-empty"
    case batteryFull = "battery-full"
    case batteryHalf = "battery-half"
    case batteryQuarter = "battery-quarter"
    case batteryThreeQuarters = "battery-three-quarters"
    case battleNet = "battle-net"
    case bedPulse = "bed-pulse"
    case bed
    case beerMugEmpty = "beer-mug-empty"
    case behance
    case bellConcierge = "bell-concierge"
    case bellSlashFill = "bell-slash.fill"
    case bellSlash = "bell-slash"
    case bellFill = "bell.fill"
    case bell
    case bezierCurve = "bezier-curve"
    case bicycle
    case bilibili
    case bimobject
    case binoculars
    case biohazard
    case bitbucket
    case bitcoinSign = "bitcoin-sign"
    case bitcoin
    case bity
    case blackTie = "black-tie"
    case blackberry
    case blenderPhone = "blender-phone"
    case blender
    case blog
    case bloggerB = "blogger-b"
    case blogger
    case bluesky
    case bluetoothB = "bluetooth-b"
    case bluetooth
    case bold
    case boltLightning = "bolt-lightning"
    case bolt
    case bomb
    case bone
    case bong
    case bookAtlas = "book-atlas"
    case bookBible = "book-bible"
    case bookBookmark = "book-bookmark"
    case bookJournalWhills = "book-journal-whills"
    case bookMedical = "book-medical"
    case bookOpenReader = "book-open-reader"
    case bookOpen = "book-open"
    case bookQuran = "book-quran"
    case bookSkull = "book-skull"
    case bookTanakh = "book-tanakh"
    case book
    case bookmarkFill = "bookmark.fill"
    case bookmark
    case bootstrap
    case borderAll = "border-all"
    case borderNone = "border-none"
    case borderTopLeft = "border-top-left"
    case boreHole = "bore-hole"
    case bots
    case bottleDroplet = "bottle-droplet"
    case bottleWater = "bottle-water"
    case bowlFood = "bowl-food"
    case bowlRice = "bowl-rice"
    case bowlingBall = "bowling-ball"
    case boxArchive = "box-archive"
    case boxOpen = "box-open"
    case boxTissue = "box-tissue"
    case box
    case boxesPacking = "boxes-packing"
    case boxesStacked = "boxes-stacked"
    case braille
    case brain
    case braveReverse = "brave-reverse"
    case brave
    case brazilianRealSign = "brazilian-real-sign"
    case breadSlice = "bread-slice"
    case bridgeCircleCheck = "bridge-circle-check"
    case bridgeCircleExclamation = "bridge-circle-exclamation"
    case bridgeCircleXmark = "bridge-circle-xmark"
    case bridgeLock = "bridge-lock"
    case bridgeWater = "bridge-water"
    case bridge
    case briefcaseMedical = "briefcase-medical"
    case briefcase
    case broomBall = "broom-ball"
    case broom
    case brush
    case btc
    case bucket
    case buffer
    case bugSlash = "bug-slash"
    case bug
    case bugs
    case buildingCircleArrowRight = "building-circle-arrow-right"
    case buildingCircleCheck = "building-circle-check"
    case buildingCircleExclamation = "building-circle-exclamation"
    case buildingCircleXmark = "building-circle-xmark"
    case buildingColumns = "building-columns"
    case buildingFlag = "building-flag"
    case buildingLock = "building-lock"
    case buildingNgo = "building-ngo"
    case buildingShield = "building-shield"
    case buildingUn = "building-un"
    case buildingUser = "building-user"
    case buildingWheat = "building-wheat"
    case buildingFill = "building.fill"
    case building
    case bullhorn
    case bullseye
    case burger
    case buromobelexperte
    case burst
    case busSimple = "bus-simple"
    case bus
    case businessTime = "business-time"
    case buyNLarge = "buy-n-large"
    case buysellads
    case c
    case cableCar = "cable-car"
    case cakeCandles = "cake-candles"
    case calculator
    case calendarCheckFill = "calendar-check.fill"
    case calendarCheck = "calendar-check"
    case calendarDay = "calendar-day"
    case calendarDaysFill = "calendar-days.fill"
    case calendarDays = "calendar-days"
    case calendarMinusFill = "calendar-minus.fill"
    case calendarMinus = "calendar-minus"
    case calendarPlusFill = "calendar-plus.fill"
    case calendarPlus = "calendar-plus"
    case calendarWeek = "calendar-week"
    case calendarXmarkFill = "calendar-xmark.fill"
    case calendarXmark = "calendar-xmark"
    case calendarFill = "calendar.fill"
    case calendar
    case cameraRetro = "camera-retro"
    case cameraRotate = "camera-rotate"
    case camera
    case campground
    case canadianMapleLeaf = "canadian-maple-leaf"
    case candyCane = "candy-cane"
    case cannabis
    case capsules
    case carBattery = "car-battery"
    case carBurst = "car-burst"
    case carOn = "car-on"
    case carRear = "car-rear"
    case carSide = "car-side"
    case carTunnel = "car-tunnel"
    case car
    case caravan
    case caretDown = "caret-down"
    case caretLeft = "caret-left"
    case caretRight = "caret-right"
    case caretUp = "caret-up"
    case carrot
    case cartArrowDown = "cart-arrow-down"
    case cartFlatbedSuitcase = "cart-flatbed-suitcase"
    case cartFlatbed = "cart-flatbed"
    case cartPlus = "cart-plus"
    case cartShopping = "cart-shopping"
    case cashRegister = "cash-register"
    case cat
    case ccAmazonPay = "cc-amazon-pay"
    case ccAmex = "cc-amex"
    case ccApplePay = "cc-apple-pay"
    case ccDinersClub = "cc-diners-club"
    case ccDiscover = "cc-discover"
    case ccJcb = "cc-jcb"
    case ccMastercard = "cc-mastercard"
    case ccPaypal = "cc-paypal"
    case ccStripe = "cc-stripe"
    case ccVisa = "cc-visa"
    case cediSign = "cedi-sign"
    case centSign = "cent-sign"
    case centercode
    case centos
    case certificate
    case chair
    case chalkboardUser = "chalkboard-user"
    case chalkboard
    case champagneGlasses = "champagne-glasses"
    case chargingStation = "charging-station"
    case chartArea = "chart-area"
    case chartBarFill = "chart-bar.fill"
    case chartBar = "chart-bar"
    case chartColumn = "chart-column"
    case chartDiagram = "chart-diagram"
    case chartGantt = "chart-gantt"
    case chartLine = "chart-line"
    case chartPie = "chart-pie"
    case chartSimple = "chart-simple"
    case checkDouble = "check-double"
    case checkToSlot = "check-to-slot"
    case check
    case cheese
    case chessBishopFill = "chess-bishop.fill"
    case chessBishop = "chess-bishop"
    case chessBoard = "chess-board"
    case chessKingFill = "chess-king.fill"
    case chessKing = "chess-king"
    case chessKnightFill = "chess-knight.fill"
    case chessKnight = "chess-knight"
    case chessPawnFill = "chess-pawn.fill"
    case chessPawn = "chess-pawn"
    case chessQueenFill = "chess-queen.fill"
    case chessQueen = "chess-queen"
    case chessRookFill = "chess-rook.fill"
    case chessRook = "chess-rook"
    case chess
    case chevronDown = "chevron-down"
    case chevronLeft = "chevron-left"
    case chevronRight = "chevron-right"
    case chevronUp = "chevron-up"
    case childCombatant = "child-combatant"
    case childDress = "child-dress"
    case childReaching = "child-reaching"
    case child
    case children
    case chrome
    case chromecast
    case church
    case circleArrowDown = "circle-arrow-down"
    case circleArrowLeft = "circle-arrow-left"
    case circleArrowRight = "circle-arrow-right"
    case circleArrowUp = "circle-arrow-up"
    case circleCheckFill = "circle-check.fill"
    case circleCheck = "circle-check"
    case circleChevronDown = "circle-chevron-down"
    case circleChevronLeft = "circle-chevron-left"
    case circleChevronRight = "circle-chevron-right"
    case circleChevronUp = "circle-chevron-up"
    case circleDollarToSlot = "circle-dollar-to-slot"
    case circleDotFill = "circle-dot.fill"
    case circleDot = "circle-dot"
    case circleDownFill = "circle-down.fill"
    case circleDown = "circle-down"
    case circleExclamation = "circle-exclamation"
    case circleH = "circle-h"
    case circleHalfStroke = "circle-half-stroke"
    case circleInfo = "circle-info"
    case circleLeftFill = "circle-left.fill"
    case circleLeft = "circle-left"
    case circleMinus = "circle-minus"
    case circleNodes = "circle-nodes"
    case circleNotch = "circle-notch"
    case circlePauseFill = "circle-pause.fill"
    case circlePause = "circle-pause"
    case circlePlayFill = "circle-play.fill"
    case circlePlay = "circle-play"
    case circlePlus = "circle-plus"
    case circleQuestionFill = "circle-question.fill"
    case circleQuestion = "circle-question"
    case circleRadiation = "circle-radiation"
    case circleRightFill = "circle-right.fill"
    case circleRight = "circle-right"
    case circleStopFill = "circle-stop.fill"
    case circleStop = "circle-stop"
    case circleUpFill = "circle-up.fill"
    case circleUp = "circle-up"
    case circleUserFill = "circle-user.fill"
    case circleUser = "circle-user"
    case circleXmarkFill = "circle-xmark.fill"
    case circleXmark = "circle-xmark"
    case circleFill = "circle.fill"
    case circle
    case city
    case clapperboard
    case clipboardCheck = "clipboard-check"
    case clipboardList = "clipboard-list"
    case clipboardQuestion = "clipboard-question"
    case clipboardUser = "clipboard-user"
    case clipboardFill = "clipboard.fill"
    case clipboard
    case clockRotateLeft = "clock-rotate-left"
    case clockFill = "clock.fill"
    case clock
    case cloneFill = "clone.fill"
    case clone
    case closedCaptioningFill = "closed-captioning.fill"
    case closedCaptioning = "closed-captioning"
    case cloudArrowDown = "cloud-arrow-down"
    case cloudArrowUp = "cloud-arrow-up"
    case cloudBolt = "cloud-bolt"
    case cloudMeatball = "cloud-meatball"
    case cloudMoonRain = "cloud-moon-rain"
    case cloudMoon = "cloud-moon"
    case cloudRain = "cloud-rain"
    case cloudShowersHeavy = "cloud-showers-heavy"
    case cloudShowersWater = "cloud-showers-water"
    case cloudSunRain = "cloud-sun-rain"
    case cloudSun = "cloud-sun"
    case cloud
    case cloudflare
    case cloudscale
    case cloudsmith
    case cloudversify
    case clover
    case cmplid
    case codeBranch = "code-branch"
    case codeCommit = "code-commit"
    case codeCompare = "code-compare"
    case codeFork = "code-fork"
    case codeMerge = "code-merge"
    case codePullRequest = "code-pull-request"
    case code
    case codepen
    case codiepie
    case coins
    case colonSign = "colon-sign"
    case commentDollar = "comment-dollar"
    case commentDotsFill = "comment-dots.fill"
    case commentDots = "comment-dots"
    case commentMedical = "comment-medical"
    case commentNodes = "comment-nodes"
    case commentSlash = "comment-slash"
    case commentSms = "comment-sms"
    case commentFill = "comment.fill"
    case comment
    case commentsDollar = "comments-dollar"
    case commentsFill = "comments.fill"
    case comments
    case compactDisc = "compact-disc"
    case compassDrafting = "compass-drafting"
    case compassFill = "compass.fill"
    case compass
    case compress
    case computerMouse = "computer-mouse"
    case computer
    case confluence
    case connectdevelop
    case contao
    case cookieBite = "cookie-bite"
    case cookie
    case copyFill = "copy.fill"
    case copy
    case copyrightFill = "copyright.fill"
    case copyright
    case cottonBureau = "cotton-bureau"
    case couch
    case cow
    case cpanel
    case creativeCommonsBy = "creative-commons-by"
    case creativeCommonsNcEu = "creative-commons-nc-eu"
    case creativeCommonsNcJp = "creative-commons-nc-jp"
    case creativeCommonsNc = "creative-commons-nc"
    case creativeCommonsNd = "creative-commons-nd"
    case creativeCommonsPdAlt = "creative-commons-pd-alt"
    case creativeCommonsPd = "creative-commons-pd"
    case creativeCommonsRemix = "creative-commons-remix"
    case creativeCommonsSa = "creative-commons-sa"
    case creativeCommonsSamplingPlus = "creative-commons-sampling-plus"
    case creativeCommonsSampling = "creative-commons-sampling"
    case creativeCommonsShare = "creative-commons-share"
    case creativeCommonsZero = "creative-commons-zero"
    case creativeCommons = "creative-commons"
    case creditCardFill = "credit-card.fill"
    case creditCard = "credit-card"
    case criticalRole = "critical-role"
    case cropSimple = "crop-simple"
    case crop
    case cross
    case crosshairs
    case crow
    case crown
    case crutch
    case cruzeiroSign = "cruzeiro-sign"
    case css
    case css3Alt = "css3-alt"
    case css3
    case cube
    case cubesStacked = "cubes-stacked"
    case cubes
    case cuttlefish
    case dAndDBeyond = "d-and-d-beyond"
    case dAndD = "d-and-d"
    case d
    case dailymotion
    case dartLang = "dart-lang"
    case dashcube
    case database
    case debian
    case deezer
    case deleteLeft = "delete-left"
    case delicious
    case democrat
    case deploydog
    case deskpro
    case desktop
    case dev
    case deviantart
    case dharmachakra
    case dhl
    case diagramNext = "diagram-next"
    case diagramPredecessor = "diagram-predecessor"
    case diagramProject = "diagram-project"
    case diagramSuccessor = "diagram-successor"
    case diamondTurnRight = "diamond-turn-right"
    case diamond
    case diaspora
    case diceD20 = "dice-d20"
    case diceD6 = "dice-d6"
    case diceFive = "dice-five"
    case diceFour = "dice-four"
    case diceOne = "dice-one"
    case diceSix = "dice-six"
    case diceThree = "dice-three"
    case diceTwo = "dice-two"
    case dice
    case digg
    case digitalOcean = "digital-ocean"
    case discord
    case discourse
    case disease
    case display
    case divide
    case dna
    case dochub
    case docker
    case dog
    case dollarSign = "dollar-sign"
    case dolly
    case dongSign = "dong-sign"
    case doorClosed = "door-closed"
    case doorOpen = "door-open"
    case dove
    case downLeftAndUpRightToCenter = "down-left-and-up-right-to-center"
    case downLong = "down-long"
    case download
    case draft2digital
    case dragon
    case drawPolygon = "draw-polygon"
    case dribbble
    case dropbox
    case dropletSlash = "droplet-slash"
    case droplet
    case drumSteelpan = "drum-steelpan"
    case drum
    case drumstickBite = "drumstick-bite"
    case drupal
    case dumbbell
    case dumpsterFire = "dumpster-fire"
    case dumpster
    case dungeon
    case dyalog
    case e
    case earDeaf = "ear-deaf"
    case earListen = "ear-listen"
    case earlybirds
    case earthAfrica = "earth-africa"
    case earthAmericas = "earth-americas"
    case earthAsia = "earth-asia"
    case earthEurope = "earth-europe"
    case earthOceania = "earth-oceania"
    case ebay
    case edgeLegacy = "edge-legacy"
    case edge
    case egg
    case eject
    case elementor
    case elevator
    case ellipsisVertical = "ellipsis-vertical"
    case ellipsis
    case ello
    case ember
    case empire
    case envelopeCircleCheck = "envelope-circle-check"
    case envelopeOpenText = "envelope-open-text"
    case envelopeOpenFill = "envelope-open.fill"
    case envelopeOpen = "envelope-open"
    case envelopeFill = "envelope.fill"
    case envelope
    case envelopesBulk = "envelopes-bulk"
    case envira
    case equals
    case eraser
    case erlang
    case ethereum
    case ethernet
    case etsy
    case euroSign = "euro-sign"
    case evernote
    case exclamation
    case expand
    case expeditedssl
    case explosion
    case eyeDropper = "eye-dropper"
    case eyeLowVision = "eye-low-vision"
    case eyeSlashFill = "eye-slash.fill"
    case eyeSlash = "eye-slash"
    case eyeFill = "eye.fill"
    case eye
    case f
    case faceAngryFill = "face-angry.fill"
    case faceAngry = "face-angry"
    case faceDizzyFill = "face-dizzy.fill"
    case faceDizzy = "face-dizzy"
    case faceFlushedFill = "face-flushed.fill"
    case faceFlushed = "face-flushed"
    case faceFrownOpenFill = "face-frown-open.fill"
    case faceFrownOpen = "face-frown-open"
    case faceFrownFill = "face-frown.fill"
    case faceFrown = "face-frown"
    case faceGrimaceFill = "face-grimace.fill"
    case faceGrimace = "face-grimace"
    case faceGrinBeamSweatFill = "face-grin-beam-sweat.fill"
    case faceGrinBeamSweat = "face-grin-beam-sweat"
    case faceGrinBeamFill = "face-grin-beam.fill"
    case faceGrinBeam = "face-grin-beam"
    case faceGrinHeartsFill = "face-grin-hearts.fill"
    case faceGrinHearts = "face-grin-hearts"
    case faceGrinSquintTearsFill = "face-grin-squint-tears.fill"
    case faceGrinSquintTears = "face-grin-squint-tears"
    case faceGrinSquintFill = "face-grin-squint.fill"
    case faceGrinSquint = "face-grin-squint"
    case faceGrinStarsFill = "face-grin-stars.fill"
    case faceGrinStars = "face-grin-stars"
    case faceGrinTearsFill = "face-grin-tears.fill"
    case faceGrinTears = "face-grin-tears"
    case faceGrinTongueSquintFill = "face-grin-tongue-squint.fill"
    case faceGrinTongueSquint = "face-grin-tongue-squint"
    case faceGrinTongueWinkFill = "face-grin-tongue-wink.fill"
    case faceGrinTongueWink = "face-grin-tongue-wink"
    case faceGrinTongueFill = "face-grin-tongue.fill"
    case faceGrinTongue = "face-grin-tongue"
    case faceGrinWideFill = "face-grin-wide.fill"
    case faceGrinWide = "face-grin-wide"
    case faceGrinWinkFill = "face-grin-wink.fill"
    case faceGrinWink = "face-grin-wink"
    case faceGrinFill = "face-grin.fill"
    case faceGrin = "face-grin"
    case faceKissBeamFill = "face-kiss-beam.fill"
    case faceKissBeam = "face-kiss-beam"
    case faceKissWinkHeartFill = "face-kiss-wink-heart.fill"
    case faceKissWinkHeart = "face-kiss-wink-heart"
    case faceKissFill = "face-kiss.fill"
    case faceKiss = "face-kiss"
    case faceLaughBeamFill = "face-laugh-beam.fill"
    case faceLaughBeam = "face-laugh-beam"
    case faceLaughSquintFill = "face-laugh-squint.fill"
    case faceLaughSquint = "face-laugh-squint"
    case faceLaughWinkFill = "face-laugh-wink.fill"
    case faceLaughWink = "face-laugh-wink"
    case faceLaughFill = "face-laugh.fill"
    case faceLaugh = "face-laugh"
    case faceMehBlankFill = "face-meh-blank.fill"
    case faceMehBlank = "face-meh-blank"
    case faceMehFill = "face-meh.fill"
    case faceMeh = "face-meh"
    case faceRollingEyesFill = "face-rolling-eyes.fill"
    case faceRollingEyes = "face-rolling-eyes"
    case faceSadCryFill = "face-sad-cry.fill"
    case faceSadCry = "face-sad-cry"
    case faceSadTearFill = "face-sad-tear.fill"
    case faceSadTear = "face-sad-tear"
    case faceSmileBeamFill = "face-smile-beam.fill"
    case faceSmileBeam = "face-smile-beam"
    case faceSmileWinkFill = "face-smile-wink.fill"
    case faceSmileWink = "face-smile-wink"
    case faceSmileFill = "face-smile.fill"
    case faceSmile = "face-smile"
    case faceSurpriseFill = "face-surprise.fill"
    case faceSurprise = "face-surprise"
    case faceTiredFill = "face-tired.fill"
    case faceTired = "face-tired"
    case facebookF = "facebook-f"
    case facebookMessenger = "facebook-messenger"
    case facebook
    case fan
    case fantasyFlightGames = "fantasy-flight-games"
    case faucetDrip = "faucet-drip"
    case faucet
    case fax
    case featherPointed = "feather-pointed"
    case feather
    case fedex
    case fedora
    case ferry
    case figma
    case fileArrowDown = "file-arrow-down"
    case fileArrowUp = "file-arrow-up"
    case fileAudioFill = "file-audio.fill"
    case fileAudio = "file-audio"
    case fileCircleCheck = "file-circle-check"
    case fileCircleExclamation = "file-circle-exclamation"
    case fileCircleMinus = "file-circle-minus"
    case fileCirclePlus = "file-circle-plus"
    case fileCircleQuestion = "file-circle-question"
    case fileCircleXmark = "file-circle-xmark"
    case fileCodeFill = "file-code.fill"
    case fileCode = "file-code"
    case fileContract = "file-contract"
    case fileCsv = "file-csv"
    case fileExcelFill = "file-excel.fill"
    case fileExcel = "file-excel"
    case fileExport = "file-export"
    case fileFragment = "file-fragment"
    case fileHalfDashed = "file-half-dashed"
    case fileImageFill = "file-image.fill"
    case fileImage = "file-image"
    case fileImport = "file-import"
    case fileInvoiceDollar = "file-invoice-dollar"
    case fileInvoice = "file-invoice"
    case fileLinesFill = "file-lines.fill"
    case fileLines = "file-lines"
    case fileMedical = "file-medical"
    case filePdfFill = "file-pdf.fill"
    case filePdf = "file-pdf"
    case filePen = "file-pen"
    case filePowerpointFill = "file-powerpoint.fill"
    case filePowerpoint = "file-powerpoint"
    case filePrescription = "file-prescription"
    case fileShield = "file-shield"
    case fileSignature = "file-signature"
    case fileVideoFill = "file-video.fill"
    case fileVideo = "file-video"
    case fileWaveform = "file-waveform"
    case fileWordFill = "file-word.fill"
    case fileWord = "file-word"
    case fileZipperFill = "file-zipper.fill"
    case fileZipper = "file-zipper"
    case fileFill = "file.fill"
    case file
    case filesPinwheel = "files-pinwheel"
    case fillDrip = "fill-drip"
    case fill
    case film
    case filterCircleDollar = "filter-circle-dollar"
    case filterCircleXmark = "filter-circle-xmark"
    case filter
    case fingerprint
    case fireBurner = "fire-burner"
    case fireExtinguisher = "fire-extinguisher"
    case fireFlameCurved = "fire-flame-curved"
    case fireFlameSimple = "fire-flame-simple"
    case fire
    case firefoxBrowser = "firefox-browser"
    case firefox
    case firstOrderAlt = "first-order-alt"
    case firstOrder = "first-order"
    case firstdraft
    case fishFins = "fish-fins"
    case fish
    case flagCheckered = "flag-checkered"
    case flagUsa = "flag-usa"
    case flagFill = "flag.fill"
    case flag
    case flaskVial = "flask-vial"
    case flask
    case flickr
    case flipboard
    case floppyDiskFill = "floppy-disk.fill"
    case floppyDisk = "floppy-disk"
    case florinSign = "florin-sign"
    case flutter
    case fly
    case folderClosedFill = "folder-closed.fill"
    case folderClosed = "folder-closed"
    case folderMinus = "folder-minus"
    case folderOpenFill = "folder-open.fill"
    case folderOpen = "folder-open"
    case folderPlus = "folder-plus"
    case folderTree = "folder-tree"
    case folderFill = "folder.fill"
    case folder
    case fontAwesomeFill = "font-awesome.fill"
    case fontAwesome = "font-awesome"
    case font
    case fonticonsFi = "fonticons-fi"
    case fonticons
    case football
    case fortAwesomeAlt = "fort-awesome-alt"
    case fortAwesome = "fort-awesome"
    case forumbee
    case forwardFast = "forward-fast"
    case forwardStep = "forward-step"
    case forward
    case foursquare
    case francSign = "franc-sign"
    case freeCodeCamp = "free-code-camp"
    case freebsd
    case frog
    case fulcrum
    case futbolFill = "futbol.fill"
    case futbol
    case g
    case galacticRepublic = "galactic-republic"
    case galacticSenate = "galactic-senate"
    case gamepad
    case gasPump = "gas-pump"
    case gaugeHigh = "gauge-high"
    case gaugeSimpleHigh = "gauge-simple-high"
    case gaugeSimple = "gauge-simple"
    case gauge
    case gavel
    case gear
    case gears
    case gemFill = "gem.fill"
    case gem
    case genderless
    case getPocket = "get-pocket"
    case ggCircle = "gg-circle"
    case gg
    case ghost
    case gift
    case gifts
    case gitAlt = "git-alt"
    case git
    case githubAlt = "github-alt"
    case github
    case gitkraken
    case gitlab
    case gitter
    case glassWaterDroplet = "glass-water-droplet"
    case glassWater = "glass-water"
    case glasses
    case glideG = "glide-g"
    case glide
    case globe
    case gofore
    case golang
    case golfBallTee = "golf-ball-tee"
    case goodreadsG = "goodreads-g"
    case goodreads
    case googleDrive = "google-drive"
    case googlePay = "google-pay"
    case googlePlay = "google-play"
    case googlePlusG = "google-plus-g"
    case googlePlus = "google-plus"
    case googleScholar = "google-scholar"
    case googleWallet = "google-wallet"
    case google
    case gopuram
    case graduationCap = "graduation-cap"
    case gratipay
    case grav
    case greaterThanEqual = "greater-than-equal"
    case greaterThan = "greater-than"
    case gripLinesVertical = "grip-lines-vertical"
    case gripLines = "grip-lines"
    case gripVertical = "grip-vertical"
    case grip
    case gripfire
    case groupArrowsRotate = "group-arrows-rotate"
    case grunt
    case guaraniSign = "guarani-sign"
    case guilded
    case guitar
    case gulp
    case gun
    case h
    case hackerNews = "hacker-news"
    case hackerrank
    case hammer
    case hamsa
    case handBackFistFill = "hand-back-fist.fill"
    case handBackFist = "hand-back-fist"
    case handDots = "hand-dots"
    case handFist = "hand-fist"
    case handHoldingDollar = "hand-holding-dollar"
    case handHoldingDroplet = "hand-holding-droplet"
    case handHoldingHand = "hand-holding-hand"
    case handHoldingHeart = "hand-holding-heart"
    case handHoldingMedical = "hand-holding-medical"
    case handHolding = "hand-holding"
    case handLizardFill = "hand-lizard.fill"
    case handLizard = "hand-lizard"
    case handMiddleFinger = "hand-middle-finger"
    case handPeaceFill = "hand-peace.fill"
    case handPeace = "hand-peace"
    case handPointDownFill = "hand-point-down.fill"
    case handPointDown = "hand-point-down"
    case handPointLeftFill = "hand-point-left.fill"
    case handPointLeft = "hand-point-left"
    case handPointRightFill = "hand-point-right.fill"
    case handPointRight = "hand-point-right"
    case handPointUpFill = "hand-point-up.fill"
    case handPointUp = "hand-point-up"
    case handPointerFill = "hand-pointer.fill"
    case handPointer = "hand-pointer"
    case handScissorsFill = "hand-scissors.fill"
    case handScissors = "hand-scissors"
    case handSparkles = "hand-sparkles"
    case handSpockFill = "hand-spock.fill"
    case handSpock = "hand-spock"
    case handFill = "hand.fill"
    case hand
    case handcuffs
    case handsAslInterpreting = "hands-asl-interpreting"
    case handsBound = "hands-bound"
    case handsBubbles = "hands-bubbles"
    case handsClapping = "hands-clapping"
    case handsHoldingChild = "hands-holding-child"
    case handsHoldingCircle = "hands-holding-circle"
    case handsHolding = "hands-holding"
    case handsPraying = "hands-praying"
    case hands
    case handshakeAngle = "handshake-angle"
    case handshakeSimpleSlash = "handshake-simple-slash"
    case handshakeSimple = "handshake-simple"
    case handshakeSlash = "handshake-slash"
    case handshakeFill = "handshake.fill"
    case handshake
    case hanukiah
    case hardDriveFill = "hard-drive.fill"
    case hardDrive = "hard-drive"
    case hashnode
    case hashtag
    case hatCowboySide = "hat-cowboy-side"
    case hatCowboy = "hat-cowboy"
    case hatWizard = "hat-wizard"
    case headSideCoughSlash = "head-side-cough-slash"
    case headSideCough = "head-side-cough"
    case headSideMask = "head-side-mask"
    case headSideVirus = "head-side-virus"
    case heading
    case headphonesSimple = "headphones-simple"
    case headphones
    case headset
    case heartCircleBolt = "heart-circle-bolt"
    case heartCircleCheck = "heart-circle-check"
    case heartCircleExclamation = "heart-circle-exclamation"
    case heartCircleMinus = "heart-circle-minus"
    case heartCirclePlus = "heart-circle-plus"
    case heartCircleXmark = "heart-circle-xmark"
    case heartCrack = "heart-crack"
    case heartPulse = "heart-pulse"
    case heartFill = "heart.fill"
    case heart
    case helicopterSymbol = "helicopter-symbol"
    case helicopter
    case helmetSafety = "helmet-safety"
    case helmetUn = "helmet-un"
    case hexagonNodesBolt = "hexagon-nodes-bolt"
    case hexagonNodes = "hexagon-nodes"
    case highlighter
    case hillAvalanche = "hill-avalanche"
    case hillRockslide = "hill-rockslide"
    case hippo
    case hips
    case hireAHelper = "hire-a-helper"
    case hive
    case hockeyPuck = "hockey-puck"
    case hollyBerry = "holly-berry"
    case hooli
    case hornbill
    case horseHead = "horse-head"
    case horse
    case hospitalUser = "hospital-user"
    case hospitalFill = "hospital.fill"
    case hospital
    case hotTubPerson = "hot-tub-person"
    case hotdog
    case hotel
    case hotjar
    case hourglassEnd = "hourglass-end"
    case hourglassHalfFill = "hourglass-half.fill"
    case hourglassHalf = "hourglass-half"
    case hourglassStart = "hourglass-start"
    case hourglassFill = "hourglass.fill"
    case hourglass
    case houseChimneyCrack = "house-chimney-crack"
    case houseChimneyMedical = "house-chimney-medical"
    case houseChimneyUser = "house-chimney-user"
    case houseChimneyWindow = "house-chimney-window"
    case houseChimney = "house-chimney"
    case houseCircleCheck = "house-circle-check"
    case houseCircleExclamation = "house-circle-exclamation"
    case houseCircleXmark = "house-circle-xmark"
    case houseCrack = "house-crack"
    case houseFire = "house-fire"
    case houseFlag = "house-flag"
    case houseFloodWaterCircleArrowRight = "house-flood-water-circle-arrow-right"
    case houseFloodWater = "house-flood-water"
    case houseLaptop = "house-laptop"
    case houseLock = "house-lock"
    case houseMedicalCircleCheck = "house-medical-circle-check"
    case houseMedicalCircleExclamation = "house-medical-circle-exclamation"
    case houseMedicalCircleXmark = "house-medical-circle-xmark"
    case houseMedicalFlag = "house-medical-flag"
    case houseMedical = "house-medical"
    case houseSignal = "house-signal"
    case houseTsunami = "house-tsunami"
    case houseUser = "house-user"
    case house
    case houzz
    case hryvniaSign = "hryvnia-sign"
    case html5
    case hubspot
    case hurricane
    case iCursor = "i-cursor"
    case i
    case iceCream = "ice-cream"
    case icicles
    case icons
    case idBadgeFill = "id-badge.fill"
    case idBadge = "id-badge"
    case idCardClip = "id-card-clip"
    case idCardFill = "id-card.fill"
    case idCard = "id-card"
    case ideal
    case igloo
    case imagePortrait = "image-portrait"
    case imageFill = "image.fill"
    case image
    case imagesFill = "images.fill"
    case images
    case imdb
    case inbox
    case indent
    case indianRupeeSign = "indian-rupee-sign"
    case industry
    case infinity
    case info
    case instagram
    case instalod
    case intercom
    case internetExplorer = "internet-explorer"
    case invision
    case ioxhost
    case italic
    case itchIo = "itch-io"
    case itunesNote = "itunes-note"
    case itunes
    case j
    case jarWheat = "jar-wheat"
    case jar
    case java
    case jediOrder = "jedi-order"
    case jedi
    case jenkins
    case jetFighterUp = "jet-fighter-up"
    case jetFighter = "jet-fighter"
    case jira
    case joget
    case joint
    case joomla
    case js
    case jsfiddle
    case jugDetergent = "jug-detergent"
    case jxl
    case k
    case kaaba
    case kaggle
    case key
    case keybase
    case keyboardFill = "keyboard.fill"
    case keyboard
    case keycdn
    case khanda
    case kickstarterK = "kickstarter-k"
    case kickstarter
    case kipSign = "kip-sign"
    case kitMedical = "kit-medical"
    case kitchenSet = "kitchen-set"
    case kiwiBird = "kiwi-bird"
    case korvue
    case l
    case landMineOn = "land-mine-on"
    case landmarkDome = "landmark-dome"
    case landmarkFlag = "landmark-flag"
    case landmark
    case language
    case laptopCode = "laptop-code"
    case laptopFile = "laptop-file"
    case laptopMedical = "laptop-medical"
    case laptop
    case laravel
    case lariSign = "lari-sign"
    case lastfm
    case layerGroup = "layer-group"
    case leaf
    case leanpub
    case leftLong = "left-long"
    case leftRight = "left-right"
    case lemonFill = "lemon.fill"
    case lemon
    case lessThanEqual = "less-than-equal"
    case lessThan = "less-than"
    case less
    case letterboxd
    case lifeRingFill = "life-ring.fill"
    case lifeRing = "life-ring"
    case lightbulbFill = "lightbulb.fill"
    case lightbulb
    case line
    case linesLeaning = "lines-leaning"
    case linkSlash = "link-slash"
    case link
    case linkedinIn = "linkedin-in"
    case linkedin
    case linode
    case linux
    case liraSign = "lira-sign"
    case listCheck = "list-check"
    case listOl = "list-ol"
    case listUl = "list-ul"
    case list
    case litecoinSign = "litecoin-sign"
    case locationArrow = "location-arrow"
    case locationCrosshairs = "location-crosshairs"
    case locationDot = "location-dot"
    case locationPinLock = "location-pin-lock"
    case locationPin = "location-pin"
    case lockOpen = "lock-open"
    case lock
    case locust
    case lungsVirus = "lungs-virus"
    case lungs
    case lyft
    case m
    case magento
    case magnet
    case magnifyingGlassArrowRight = "magnifying-glass-arrow-right"
    case magnifyingGlassChart = "magnifying-glass-chart"
    case magnifyingGlassDollar = "magnifying-glass-dollar"
    case magnifyingGlassLocation = "magnifying-glass-location"
    case magnifyingGlassMinus = "magnifying-glass-minus"
    case magnifyingGlassPlus = "magnifying-glass-plus"
    case magnifyingGlass = "magnifying-glass"
    case mailchimp
    case manatSign = "manat-sign"
    case mandalorian
    case mapLocationDot = "map-location-dot"
    case mapLocation = "map-location"
    case mapPin = "map-pin"
    case mapFill = "map.fill"
    case map
    case markdown
    case marker
    case marsAndVenusBurst = "mars-and-venus-burst"
    case marsAndVenus = "mars-and-venus"
    case marsDouble = "mars-double"
    case marsStrokeRight = "mars-stroke-right"
    case marsStrokeUp = "mars-stroke-up"
    case marsStroke = "mars-stroke"
    case mars
    case martiniGlassCitrus = "martini-glass-citrus"
    case martiniGlassEmpty = "martini-glass-empty"
    case martiniGlass = "martini-glass"
    case maskFace = "mask-face"
    case maskVentilator = "mask-ventilator"
    case mask
    case masksTheater = "masks-theater"
    case mastodon
    case mattressPillow = "mattress-pillow"
    case maxcdn
    case maximize
    case mdb
    case medal
    case medapps
    case medium
    case medrt
    case meetup
    case megaport
    case memory
    case mendeley
    case menorah
    case mercury
    case messageFill = "message.fill"
    case message
    case meta
    case meteor
    case microblog
    case microchip
    case microphoneLinesSlash = "microphone-lines-slash"
    case microphoneLines = "microphone-lines"
    case microphoneSlash = "microphone-slash"
    case microphone
    case microscope
    case microsoft
    case millSign = "mill-sign"
    case minimize
    case mintbit
    case minus
    case mitten
    case mix
    case mixcloud
    case mixer
    case mizuni
    case mobileButton = "mobile-button"
    case mobileRetro = "mobile-retro"
    case mobileScreenButton = "mobile-screen-button"
    case mobileScreen = "mobile-screen"
    case mobile
    case modx
    case monero
    case moneyBill1Wave = "money-bill-1-wave"
    case moneyBill1Fill = "money-bill-1.fill"
    case moneyBill1 = "money-bill-1"
    case moneyBillTransfer = "money-bill-transfer"
    case moneyBillTrendUp = "money-bill-trend-up"
    case moneyBillWave = "money-bill-wave"
    case moneyBillWheat = "money-bill-wheat"
    case moneyBill = "money-bill"
    case moneyBills = "money-bills"
    case moneyCheckDollar = "money-check-dollar"
    case moneyCheck = "money-check"
    case monument
    case moonFill = "moon.fill"
    case moon
    case mortarPestle = "mortar-pestle"
    case mosque
    case mosquitoNet = "mosquito-net"
    case mosquito
    case motorcycle
    case mound
    case mountainCity = "mountain-city"
    case mountainSun = "mountain-sun"
    case mountain
    case mugHot = "mug-hot"
    case mugSaucer = "mug-saucer"
    case music
    case n
    case nairaSign = "naira-sign"
    case napster
    case neos
    case networkWired = "network-wired"
    case neuter
    case newspaperFill = "newspaper.fill"
    case newspaper
    case nfcDirectional = "nfc-directional"
    case nfcSymbol = "nfc-symbol"
    case nimblr
    case nodeJs = "node-js"
    case node
    case notEqual = "not-equal"
    case notdef
    case noteStickyFill = "note-sticky.fill"
    case noteSticky = "note-sticky"
    case notesMedical = "notes-medical"
    case npm
    case ns8
    case nutritionix
    case o
    case objectGroupFill = "object-group.fill"
    case objectGroup = "object-group"
    case objectUngroupFill = "object-ungroup.fill"
    case objectUngroup = "object-ungroup"
    case octopusDeploy = "octopus-deploy"
    case odnoklassniki
    case odysee
    case oilCan = "oil-can"
    case oilWell = "oil-well"
    case oldRepublic = "old-republic"
    case om
    case opencart
    case openid
    case opensuse
    case opera
    case optinMonster = "optin-monster"
    case orcid
    case osi
    case otter
    case outdent
    case p
    case padlet
    case page4
    case pagelines
    case pager
    case paintRoller = "paint-roller"
    case paintbrush
    case palette
    case palfed
    case pallet
    case panorama
    case paperPlaneFill = "paper-plane.fill"
    case paperPlane = "paper-plane"
    case paperclip
    case parachuteBox = "parachute-box"
    case paragraph
    case passport
    case pasteFill = "paste.fill"
    case paste
    case patreon
    case pause
    case paw
    case paypal
    case peace
    case penClip = "pen-clip"
    case penFancy = "pen-fancy"
    case penNib = "pen-nib"
    case penRuler = "pen-ruler"
    case penToSquareFill = "pen-to-square.fill"
    case penToSquare = "pen-to-square"
    case pen
    case pencil
    case peopleArrows = "people-arrows"
    case peopleCarryBox = "people-carry-box"
    case peopleGroup = "people-group"
    case peopleLine = "people-line"
    case peoplePulling = "people-pulling"
    case peopleRobbery = "people-robbery"
    case peopleRoof = "people-roof"
    case pepperHot = "pepper-hot"
    case perbyte
    case percent
    case periscope
    case personArrowDownToLine = "person-arrow-down-to-line"
    case personArrowUpFromLine = "person-arrow-up-from-line"
    case personBiking = "person-biking"
    case personBooth = "person-booth"
    case personBreastfeeding = "person-breastfeeding"
    case personBurst = "person-burst"
    case personCane = "person-cane"
    case personChalkboard = "person-chalkboard"
    case personCircleCheck = "person-circle-check"
    case personCircleExclamation = "person-circle-exclamation"
    case personCircleMinus = "person-circle-minus"
    case personCirclePlus = "person-circle-plus"
    case personCircleQuestion = "person-circle-question"
    case personCircleXmark = "person-circle-xmark"
    case personDigging = "person-digging"
    case personDotsFromLine = "person-dots-from-line"
    case personDressBurst = "person-dress-burst"
    case personDress = "person-dress"
    case personDrowning = "person-drowning"
    case personFallingBurst = "person-falling-burst"
    case personFalling = "person-falling"
    case personHalfDress = "person-half-dress"
    case personHarassing = "person-harassing"
    case personHiking = "person-hiking"
    case personMilitaryPointing = "person-military-pointing"
    case personMilitaryRifle = "person-military-rifle"
    case personMilitaryToPerson = "person-military-to-person"
    case personPraying = "person-praying"
    case personPregnant = "person-pregnant"
    case personRays = "person-rays"
    case personRifle = "person-rifle"
    case personRunning = "person-running"
    case personShelter = "person-shelter"
    case personSkating = "person-skating"
    case personSkiingNordic = "person-skiing-nordic"
    case personSkiing = "person-skiing"
    case personSnowboarding = "person-snowboarding"
    case personSwimming = "person-swimming"
    case personThroughWindow = "person-through-window"
    case personWalkingArrowLoopLeft = "person-walking-arrow-loop-left"
    case personWalkingArrowRight = "person-walking-arrow-right"
    case personWalkingDashedLineArrowRight = "person-walking-dashed-line-arrow-right"
    case personWalkingLuggage = "person-walking-luggage"
    case personWalkingWithCane = "person-walking-with-cane"
    case personWalking = "person-walking"
    case person
    case pesetaSign = "peseta-sign"
    case pesoSign = "peso-sign"
    case phabricator
    case phoenixFramework = "phoenix-framework"
    case phoenixSquadron = "phoenix-squadron"
    case phoneFlip = "phone-flip"
    case phoneSlash = "phone-slash"
    case phoneVolume = "phone-volume"
    case phone
    case photoFilm = "photo-film"
    case php
    case piedPiperAlt = "pied-piper-alt"
    case piedPiperHat = "pied-piper-hat"
    case piedPiperPp = "pied-piper-pp"
    case piedPiper = "pied-piper"
    case piggyBank = "piggy-bank"
    case pills
    case pinterestP = "pinterest-p"
    case pinterest
    case pix
    case pixiv
    case pizzaSlice = "pizza-slice"
    case placeOfWorship = "place-of-worship"
    case planeArrival = "plane-arrival"
    case planeCircleCheck = "plane-circle-check"
    case planeCircleExclamation = "plane-circle-exclamation"
    case planeCircleXmark = "plane-circle-xmark"
    case planeDeparture = "plane-departure"
    case planeLock = "plane-lock"
    case planeSlash = "plane-slash"
    case planeUp = "plane-up"
    case plane
    case plantWilt = "plant-wilt"
    case plateWheat = "plate-wheat"
    case play
    case playstation
    case plugCircleBolt = "plug-circle-bolt"
    case plugCircleCheck = "plug-circle-check"
    case plugCircleExclamation = "plug-circle-exclamation"
    case plugCircleMinus = "plug-circle-minus"
    case plugCirclePlus = "plug-circle-plus"
    case plugCircleXmark = "plug-circle-xmark"
    case plug
    case plusMinus = "plus-minus"
    case plus
    case podcast
    case pooStorm = "poo-storm"
    case poo
    case poop
    case powerOff = "power-off"
    case prescriptionBottleMedical = "prescription-bottle-medical"
    case prescriptionBottle = "prescription-bottle"
    case prescription
    case print
    case productHunt = "product-hunt"
    case pumpMedical = "pump-medical"
    case pumpSoap = "pump-soap"
    case pushed
    case puzzlePiece = "puzzle-piece"
    case python
    case q
    case qq
    case qrcode
    case question
    case quinscape
    case quora
    case quoteLeft = "quote-left"
    case quoteRight = "quote-right"
    case rProject = "r-project"
    case r
    case radiation
    case radio
    case rainbow
    case rankingStar = "ranking-star"
    case raspberryPi = "raspberry-pi"
    case ravelry
    case react
    case reacteurope
    case readme
    case rebel
    case receipt
    case recordVinyl = "record-vinyl"
    case rectangleAd = "rectangle-ad"
    case rectangleListFill = "rectangle-list.fill"
    case rectangleList = "rectangle-list"
    case rectangleXmarkFill = "rectangle-xmark.fill"
    case rectangleXmark = "rectangle-xmark"
    case recycle
    case redRiver = "red-river"
    case redditAlien = "reddit-alien"
    case reddit
    case redhat
    case registeredFill = "registered.fill"
    case registered
    case renren
    case `repeat`
    case replyAll = "reply-all"
    case reply
    case replyd
    case republican
    case researchgate
    case resolving
    case restroom
    case retweet
    case rev
    case ribbon
    case rightFromBracket = "right-from-bracket"
    case rightLeft = "right-left"
    case rightLong = "right-long"
    case rightToBracket = "right-to-bracket"
    case ring
    case roadBarrier = "road-barrier"
    case roadBridge = "road-bridge"
    case roadCircleCheck = "road-circle-check"
    case roadCircleExclamation = "road-circle-exclamation"
    case roadCircleXmark = "road-circle-xmark"
    case roadLock = "road-lock"
    case roadSpikes = "road-spikes"
    case road
    case robot
    case rocket
    case rocketchat
    case rockrms
    case rotateLeft = "rotate-left"
    case rotateRight = "rotate-right"
    case rotate
    case route
    case rss
    case rubleSign = "ruble-sign"
    case rug
    case rulerCombined = "ruler-combined"
    case rulerHorizontal = "ruler-horizontal"
    case rulerVertical = "ruler-vertical"
    case ruler
    case rupeeSign = "rupee-sign"
    case rupiahSign = "rupiah-sign"
    case rust
    case s
    case sackDollar = "sack-dollar"
    case sackXmark = "sack-xmark"
    case safari
    case sailboat
    case salesforce
    case sass
    case satelliteDish = "satellite-dish"
    case satellite
    case scaleBalanced = "scale-balanced"
    case scaleUnbalancedFlip = "scale-unbalanced-flip"
    case scaleUnbalanced = "scale-unbalanced"
    case schlix
    case schoolCircleCheck = "school-circle-check"
    case schoolCircleExclamation = "school-circle-exclamation"
    case schoolCircleXmark = "school-circle-xmark"
    case schoolFlag = "school-flag"
    case schoolLock = "school-lock"
    case school
    case scissors
    case screenpal
    case screwdriverWrench = "screwdriver-wrench"
    case screwdriver
    case scribd
    case scrollTorah = "scroll-torah"
    case scroll
    case sdCard = "sd-card"
    case searchengin
    case section
    case seedling
    case sellcast
    case sellsy
    case server
    case servicestack
    case shapes
    case shareFromSquareFill = "share-from-square.fill"
    case shareFromSquare = "share-from-square"
    case shareNodes = "share-nodes"
    case share
    case sheetPlastic = "sheet-plastic"
    case shekelSign = "shekel-sign"
    case shieldCat = "shield-cat"
    case shieldDog = "shield-dog"
    case shieldHalved = "shield-halved"
    case shieldHeart = "shield-heart"
    case shieldVirus = "shield-virus"
    case shield
    case ship
    case shirt
    case shirtsinbulk
    case shoePrints = "shoe-prints"
    case shoelace
    case shopLock = "shop-lock"
    case shopSlash = "shop-slash"
    case shop
    case shopify
    case shopware
    case shower
    case shrimp
    case shuffle
    case shuttleSpace = "shuttle-space"
    case signHanging = "sign-hanging"
    case signalMessenger = "signal-messenger"
    case signal
    case signature
    case signsPost = "signs-post"
    case simCard = "sim-card"
    case simplybuilt
    case sink
    case sistrix
    case sitemap
    case sith
    case sitrox
    case sketch
    case skullCrossbones = "skull-crossbones"
    case skull
    case skyatlas
    case skype
    case slack
    case slash
    case sleigh
    case sliders
    case slideshare
    case smog
    case smoking
    case snapchat
    case snowflakeFill = "snowflake.fill"
    case snowflake
    case snowman
    case snowplow
    case soap
    case socks
    case solarPanel = "solar-panel"
    case sortDown = "sort-down"
    case sortUp = "sort-up"
    case sort
    case soundcloud
    case sourcetree
    case spa
    case spaceAwesome = "space-awesome"
    case spaghettiMonsterFlying = "spaghetti-monster-flying"
    case speakap
    case speakerDeck = "speaker-deck"
    case spellCheck = "spell-check"
    case spider
    case spinner
    case splotch
    case spoon
    case spotify
    case sprayCanSparkles = "spray-can-sparkles"
    case sprayCan = "spray-can"
    case squareArrowUpRight = "square-arrow-up-right"
    case squareBehance = "square-behance"
    case squareBinary = "square-binary"
    case squareBluesky = "square-bluesky"
    case squareCaretDownFill = "square-caret-down.fill"
    case squareCaretDown = "square-caret-down"
    case squareCaretLeftFill = "square-caret-left.fill"
    case squareCaretLeft = "square-caret-left"
    case squareCaretRightFill = "square-caret-right.fill"
    case squareCaretRight = "square-caret-right"
    case squareCaretUpFill = "square-caret-up.fill"
    case squareCaretUp = "square-caret-up"
    case squareCheckFill = "square-check.fill"
    case squareCheck = "square-check"
    case squareDribbble = "square-dribbble"
    case squareEnvelope = "square-envelope"
    case squareFacebook = "square-facebook"
    case squareFontAwesomeStroke = "square-font-awesome-stroke"
    case squareFontAwesome = "square-font-awesome"
    case squareFullFill = "square-full.fill"
    case squareFull = "square-full"
    case squareGit = "square-git"
    case squareGithub = "square-github"
    case squareGitlab = "square-gitlab"
    case squareGooglePlus = "square-google-plus"
    case squareH = "square-h"
    case squareHackerNews = "square-hacker-news"
    case squareInstagram = "square-instagram"
    case squareJs = "square-js"
    case squareLastfm = "square-lastfm"
    case squareLetterboxd = "square-letterboxd"
    case squareMinusFill = "square-minus.fill"
    case squareMinus = "square-minus"
    case squareNfi = "square-nfi"
    case squareOdnoklassniki = "square-odnoklassniki"
    case squareParking = "square-parking"
    case squarePen = "square-pen"
    case squarePersonConfined = "square-person-confined"
    case squarePhoneFlip = "square-phone-flip"
    case squarePhone = "square-phone"
    case squarePiedPiper = "square-pied-piper"
    case squarePinterest = "square-pinterest"
    case squarePlusFill = "square-plus.fill"
    case squarePlus = "square-plus"
    case squarePollHorizontal = "square-poll-horizontal"
    case squarePollVertical = "square-poll-vertical"
    case squareReddit = "square-reddit"
    case squareRootVariable = "square-root-variable"
    case squareRss = "square-rss"
    case squareShareNodes = "square-share-nodes"
    case squareSnapchat = "square-snapchat"
    case squareSteam = "square-steam"
    case squareThreads = "square-threads"
    case squareTumblr = "square-tumblr"
    case squareTwitter = "square-twitter"
    case squareUpRight = "square-up-right"
    case squareUpwork = "square-upwork"
    case squareViadeo = "square-viadeo"
    case squareVimeo = "square-vimeo"
    case squareVirus = "square-virus"
    case squareWebAwesomeStroke = "square-web-awesome-stroke"
    case squareWebAwesome = "square-web-awesome"
    case squareWhatsapp = "square-whatsapp"
    case squareXTwitter = "square-x-twitter"
    case squareXing = "square-xing"
    case squareXmark = "square-xmark"
    case squareYoutube = "square-youtube"
    case squareFill = "square.fill"
    case square
    case squarespace
    case stackExchange = "stack-exchange"
    case stackOverflow = "stack-overflow"
    case stackpath
    case staffSnake = "staff-snake"
    case stairs
    case stamp
    case stapler
    case starAndCrescent = "star-and-crescent"
    case starHalfStrokeFill = "star-half-stroke.fill"
    case starHalfStroke = "star-half-stroke"
    case starHalfFill = "star-half.fill"
    case starHalf = "star-half"
    case starOfDavid = "star-of-david"
    case starOfLife = "star-of-life"
    case starFill = "star.fill"
    case star
    case staylinked
    case steamSymbol = "steam-symbol"
    case steam
    case sterlingSign = "sterling-sign"
    case stethoscope
    case stickerMule = "sticker-mule"
    case stop
    case stopwatch20 = "stopwatch-20"
    case stopwatch
    case storeSlash = "store-slash"
    case store
    case strava
    case streetView = "street-view"
    case strikethrough
    case stripeS = "stripe-s"
    case stripe
    case stroopwafel
    case stubber
    case studiovinari
    case stumbleuponCircle = "stumbleupon-circle"
    case stumbleupon
    case `subscript`
    case suitcaseMedical = "suitcase-medical"
    case suitcaseRolling = "suitcase-rolling"
    case suitcase
    case sunPlantWilt = "sun-plant-wilt"
    case sunFill = "sun.fill"
    case sun
    case superpowers
    case superscript
    case supple
    case suse
    case swatchbook
    case swift
    case symfony
    case synagogue
    case syringe
    case t
    case tableCellsColumnLock = "table-cells-column-lock"
    case tableCellsLarge = "table-cells-large"
    case tableCellsRowLock = "table-cells-row-lock"
    case tableCellsRowUnlock = "table-cells-row-unlock"
    case tableCells = "table-cells"
    case tableColumns = "table-columns"
    case tableList = "table-list"
    case tableTennisPaddleBall = "table-tennis-paddle-ball"
    case table
    case tabletButton = "tablet-button"
    case tabletScreenButton = "tablet-screen-button"
    case tablet
    case tablets
    case tachographDigital = "tachograph-digital"
    case tag
    case tags
    case tape
    case tarpDroplet = "tarp-droplet"
    case tarp
    case taxi
    case teamspeak
    case teethOpen = "teeth-open"
    case teeth
    case telegram
    case temperatureArrowDown = "temperature-arrow-down"
    case temperatureArrowUp = "temperature-arrow-up"
    case temperatureEmpty = "temperature-empty"
    case temperatureFull = "temperature-full"
    case temperatureHalf = "temperature-half"
    case temperatureHigh = "temperature-high"
    case temperatureLow = "temperature-low"
    case temperatureQuarter = "temperature-quarter"
    case temperatureThreeQuarters = "temperature-three-quarters"
    case tencentWeibo = "tencent-weibo"
    case tengeSign = "tenge-sign"
    case tentArrowDownToLine = "tent-arrow-down-to-line"
    case tentArrowLeftRight = "tent-arrow-left-right"
    case tentArrowTurnLeft = "tent-arrow-turn-left"
    case tentArrowsDown = "tent-arrows-down"
    case tent
    case tents
    case terminal
    case textHeight = "text-height"
    case textSlash = "text-slash"
    case textWidth = "text-width"
    case theRedYeti = "the-red-yeti"
    case themeco
    case themeisle
    case thermometer
    case thinkPeaks = "think-peaks"
    case threads
    case thumbsDownFill = "thumbs-down.fill"
    case thumbsDown = "thumbs-down"
    case thumbsUpFill = "thumbs-up.fill"
    case thumbsUp = "thumbs-up"
    case thumbtackSlash = "thumbtack-slash"
    case thumbtack
    case ticketSimple = "ticket-simple"
    case ticket
    case tiktok
    case timeline
    case toggleOff = "toggle-off"
    case toggleOn = "toggle-on"
    case toiletPaperSlash = "toilet-paper-slash"
    case toiletPaper = "toilet-paper"
    case toiletPortable = "toilet-portable"
    case toilet
    case toiletsPortable = "toilets-portable"
    case toolbox
    case tooth
    case toriiGate = "torii-gate"
    case tornado
    case towerBroadcast = "tower-broadcast"
    case towerCell = "tower-cell"
    case towerObservation = "tower-observation"
    case tractor
    case tradeFederation = "trade-federation"
    case trademark
    case trafficLight = "traffic-light"
    case trailer
    case trainSubway = "train-subway"
    case trainTram = "train-tram"
    case train
    case transgender
    case trashArrowUp = "trash-arrow-up"
    case trashCanArrowUp = "trash-can-arrow-up"
    case trashCanFill = "trash-can.fill"
    case trashCan = "trash-can"
    case trash
    case treeCity = "tree-city"
    case tree
    case trello
    case triangleExclamation = "triangle-exclamation"
    case trophy
    case trowelBricks = "trowel-bricks"
    case trowel
    case truckArrowRight = "truck-arrow-right"
    case truckDroplet = "truck-droplet"
    case truckFast = "truck-fast"
    case truckFieldUn = "truck-field-un"
    case truckField = "truck-field"
    case truckFront = "truck-front"
    case truckMedical = "truck-medical"
    case truckMonster = "truck-monster"
    case truckMoving = "truck-moving"
    case truckPickup = "truck-pickup"
    case truckPlane = "truck-plane"
    case truckRampBox = "truck-ramp-box"
    case truck
    case tty
    case tumblr
    case turkishLiraSign = "turkish-lira-sign"
    case turnDown = "turn-down"
    case turnUp = "turn-up"
    case tv
    case twitch
    case twitter
    case typo3
    case u
    case uber
    case ubuntu
    case uikit
    case umbraco
    case umbrellaBeach = "umbrella-beach"
    case umbrella
    case uncharted
    case underline
    case uniregistry
    case unity
    case universalAccess = "universal-access"
    case unlockKeyhole = "unlock-keyhole"
    case unlock
    case unsplash
    case untappd
    case upDownLeftRight = "up-down-left-right"
    case upDown = "up-down"
    case upLong = "up-long"
    case upRightAndDownLeftFromCenter = "up-right-and-down-left-from-center"
    case upRightFromSquare = "up-right-from-square"
    case upload
    case ups
    case upwork
    case usb
    case userAstronaut = "user-astronaut"
    case userCheck = "user-check"
    case userClock = "user-clock"
    case userDoctor = "user-doctor"
    case userGear = "user-gear"
    case userGraduate = "user-graduate"
    case userGroup = "user-group"
    case userInjured = "user-injured"
    case userLargeSlash = "user-large-slash"
    case userLarge = "user-large"
    case userLock = "user-lock"
    case userMinus = "user-minus"
    case userNinja = "user-ninja"
    case userNurse = "user-nurse"
    case userPen = "user-pen"
    case userPlus = "user-plus"
    case userSecret = "user-secret"
    case userShield = "user-shield"
    case userSlash = "user-slash"
    case userTag = "user-tag"
    case userTie = "user-tie"
    case userXmark = "user-xmark"
    case userFill = "user.fill"
    case user
    case usersBetweenLines = "users-between-lines"
    case usersGear = "users-gear"
    case usersLine = "users-line"
    case usersRays = "users-rays"
    case usersRectangle = "users-rectangle"
    case usersSlash = "users-slash"
    case usersViewfinder = "users-viewfinder"
    case users
    case usps
    case ussunnah
    case utensils
    case v
    case vaadin
    case vanShuttle = "van-shuttle"
    case vault
    case vectorSquare = "vector-square"
    case venusDouble = "venus-double"
    case venusMars = "venus-mars"
    case venus
    case vestPatches = "vest-patches"
    case vest
    case viacoin
    case viadeo
    case vialCircleCheck = "vial-circle-check"
    case vialVirus = "vial-virus"
    case vial
    case vials
    case viber
    case videoSlash = "video-slash"
    case video
    case vihara
    case vimeoV = "vimeo-v"
    case vimeo
    case vine
    case virusCovidSlash = "virus-covid-slash"
    case virusCovid = "virus-covid"
    case virusSlash = "virus-slash"
    case virus
    case viruses
    case vk
    case vnv
    case voicemail
    case volcano
    case volleyball
    case volumeHigh = "volume-high"
    case volumeLow = "volume-low"
    case volumeOff = "volume-off"
    case volumeXmark = "volume-xmark"
    case vrCardboard = "vr-cardboard"
    case vuejs
    case w
    case walkieTalkie = "walkie-talkie"
    case wallet
    case wandMagicSparkles = "wand-magic-sparkles"
    case wandMagic = "wand-magic"
    case wandSparkles = "wand-sparkles"
    case warehouse
    case watchmanMonitoring = "watchman-monitoring"
    case waterLadder = "water-ladder"
    case water
    case waveSquare = "wave-square"
    case waze
    case webAwesomeFill = "web-awesome.fill"
    case webAwesome = "web-awesome"
    case webflow
    case weebly
    case weibo
    case weightHanging = "weight-hanging"
    case weightScale = "weight-scale"
    case weixin
    case whatsapp
    case wheatAwnCircleExclamation = "wheat-awn-circle-exclamation"
    case wheatAwn = "wheat-awn"
    case wheelchairMove = "wheelchair-move"
    case wheelchair
    case whiskeyGlass = "whiskey-glass"
    case whmcs
    case wifi
    case wikipediaW = "wikipedia-w"
    case wind
    case windowMaximizeFill = "window-maximize.fill"
    case windowMaximize = "window-maximize"
    case windowMinimizeFill = "window-minimize.fill"
    case windowMinimize = "window-minimize"
    case windowRestoreFill = "window-restore.fill"
    case windowRestore = "window-restore"
    case windows
    case wineBottle = "wine-bottle"
    case wineGlassEmpty = "wine-glass-empty"
    case wineGlass = "wine-glass"
    case wirsindhandwerk
    case wix
    case wizardsOfTheCoast = "wizards-of-the-coast"
    case wodu
    case wolfPackBattalion = "wolf-pack-battalion"
    case wonSign = "won-sign"
    case wordpressSimple = "wordpress-simple"
    case wordpress
    case worm
    case wpbeginner
    case wpexplorer
    case wpforms
    case wpressr
    case wrench
    case xRay = "x-ray"
    case xTwitter = "x-twitter"
    case x
    case xbox
    case xing
    case xmark
    case xmarksLines = "xmarks-lines"
    case yCombinator = "y-combinator"
    case y
    case yahoo
    case yammer
    case yandexInternational = "yandex-international"
    case yandex
    case yarn
    case yelp
    case yenSign = "yen-sign"
    case yinYang = "yin-yang"
    case yoast
    case youtube
    case z
    case zhihu
}
